##############################################################################################
### playbook to deploy the mcx switch
### Use this playbook to deploy the console configurations of mcx switch in SONiC testbed
################################################################################################
- name: Get inventory name
  set_fact: inv_name={{ inventory_file.split("/")[-1] }}

- name: Gathering lab graph facts about the device
  conn_graph_facts: hosts={{ groups[inv_name] }} ignore_errors=True
  delegate_to: localhost
  tags: always

- name: Check that OS is SONiC
  fail: msg="Cannot confirm OS is SONiC"
  when: os is not defined or os != "sonic"

- name: Prepare mgmt device admin login info
  set_fact: ansible_ssh_user={{ mgmt_admin_user }} ansible_ssh_pass={{ mgmt_admin_password }}

- name: If dry_run and reset, use dry_run_reset.yml
  import_tasks: dry_run_reset.yml
  when: dry_run is defined and reset is defined

- name: If dry_run and not reset, use dry_run_incremental.yml
  import_tasks: dry_run_incremental.yml
  when: dry_run is defined and reset is not defined

- name: If reset setting, use reset_update.yml
  import_tasks: reset_update.yml
  when: reset is defined and dry_run is not defined

- name: If reset is not set, use incremental_update.yml
  import_tasks: incremental_update.yml
  when: reset is not defined and dry_run is not defined
