ansible_connection: multi_passwd_ssh

ansible_ssh_user: "{{ secret_group_vars['l1_switch']['ansible_ssh_user'] }}"
ansible_ssh_pass: "{{ secret_group_vars['l1_switch']['ansible_ssh_pass'] }}"
ansible_altpasswords: "{{ secret_group_vars['l1_switch']['altpasswords'] }}"
