# upgrade cEOS to 4.25.5.1M from 4.23.2F at 2021/09/24

#ceos_image_filename: cEOS64-lab-4.23.2F.tar.xz
#ceos_image_orig: ceosimage:4.23.2F
#ceos_image: ceosimage:4.23.2F-1
ceos_image_filename: cEOS64-lab-4.25.5.1M.tar
ceos_image_orig: ceosimage:4.25.5.1M
ceos_image: ceosimage:4.25.5.1M-1
skip_ceos_image_downloading: false
