eos_default_login: "admin"
eos_default_password: ""
eos_login: admin
eos_password: 123456
eos_root_user: root
eos_root_password: 123456

junos_default_login: "root"
junos_default_password:  ""
junos_login: "root"
junos_password: ""

cisco_login: "admin"
cisco_password: "password"

sonic_login: "admin"
sonic_default_passwords:
 - "YourPaSsWoRd"
 - "password"
 - "admin"
sonic_password: "password"

k8s_master_login: "ubuntu"
k8s_master_password: "use_own_value"

ptf_host_user: root
ptf_host_pass: root

vm_host_user: use_own_value
vm_host_password: use_own_value
vm_host_become_password: use_own_value
