eos_default_login: "admin"
eos_default_password: ""
eos_login: admin
eos_password: 123456
eos_root_user: root
eos_root_password: 123456

sonic_login: "admin"
sonic_default_passwords:
 - "YourPaSsWoRd"
 - "password"
sonic_password: "password"

k8s_master_login: "ubuntu"
k8s_master_password: "use_own_value"

ptf_host_user: root
ptf_host_pass: root
