# if your lab needs http(s) proxy to access Internet
# Uncomment following section and provide correct http(s) proxy
proxy_env:
  http_proxy: http://100.127.20.21:8080
  https_proxy: http://100.127.20.21:8080
  no_proxy: localhost,127.0.0.1,acs-repo.corp.microsoft.com
