---
# Specify all public mappings below
lab: lab_connection_graph.xml
example_ixia: example_ixia_connection_graph.xml



# Specify all internal mappings below
str: starlab_connection_graph.xml
str2: spytest_connection_graph.xml
str3: str3test_connection_graph.xml
