name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

resources:
  repositories:
  - repository: https://mssonic@dev.azure.com/mssonic/internal/_git/sonic-metadata
    type: git
    name: sonic-metadata
    ref: master

schedules:
  - cron: "0 1 * * 2,5"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal-202012
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms64-t0-s6100-1
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_202012)
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_BRCM_202012)
    displayName: "py_saithrift URL"

  # Testbed specific, to skip and/or include directories
  - name: TESTBED_SPECIFIC
    type: string
    default: '-S "pfc_asym span sub_port_interfaces platform_tests pfcwd fdb qos acl crm pc copp metadata-scripts"'
    displayName: Testbed specific

  # Custom skip scripts
  - name: SKIP_SCRIPTS
    type: string
    default: "platform_tests/test_advanced_reboot.py::test_warm_reboot \
              platform_tests/test_advanced_reboot.py::test_warm_reboot_mac_jump \
              platform_tests/test_advanced_reboot.py::test_warm_reboot_sad"
    displayName: "Skip Scripts"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      TESTBED_SPECIFIC: ${{ parameters.TESTBED_SPECIFIC }}
      SKIP_SCRIPTS: ${{ parameters.SKIP_SCRIPTS }}
