name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 4 * * 1,3,5"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms7-t0-s6100
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_PUBLIC)
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_BRCM_PUBLIC)
    displayName: "py_saithrift URL"

  - name: SKIP_SCRIPTS
    type: string
    default: "test_reboot.py::test_watchdog_reboot"
    displayName: "Skip Scripts"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      SKIP_SCRIPTS: ${{ parameters.SKIP_SCRIPTS }}
