---
#testlab (lab) group variables
# file: group_vars/lab.yml

# ntp variables
ntp_servers: ['10.0.0.1', '10.0.0.2']

# syslog variables
syslog_servers: ['10.0.0.5', '10.0.0.6']

# dns variables
dns_servers: ['10.0.0.5', '10.0.0.6']

# forced_mgmt_routes
forced_mgmt_routes: ['172.17.0.1/24']

# ErspanDestinationIpv4
erspan_dest: ['10.0.0.7']

radius_servers: []

radius_passkey: testing123

# It can be a real lab tacacs server.
tacacs_servers: ['172.17.0.6']
tacacs_passkey: testing123

# tacacs grous
tacacs_group: 'testlab'

# Determine whether enable tacacs authentication during deploy-minigraph. If false, use local authentication.
# If yes, authenticate using servers configured in `tacacs_servers`
tacacs_enabled_by_default: false

# snmp servers
snmp_servers: ['10.0.0.9']

# dhcp relay servers
dhcp_servers: ['192.0.0.1', '192.0.0.2', '192.0.0.3', '192.0.0.4']

# dhcpv6 relay servers
dhcpv6_servers: ['fc02:2000::1', 'fc02:2000::2', 'fc02:2000::3', 'fc02:2000::4']

# snmp variables
snmp_rocommunity: public
snmp_location: testlab

# bgp slb passive range
bgp_slb_passive_range: 10.255.0.0/25

#For Arista fanout switch deployment only
fanout_admin_user: "fanoutadminuser"
fanout_admin_password: "fanoutadminpassword"

mgmt_admin_user: "mgmtadminuser"
mgmt_admin_password: "mgmtadminpassword"
