ansible_ssh_pass: cisco123
ansible_become_pass: cisco123
sonicadmin_user: cisco
sonicadmin_password: cisco123
sonicadmin_initial_password: cisco123

console_login:
  console_telnet:
    user: "root"
    passwd: ["password1", "password2"]
  console_ssh:
    user: "root"
    passwd: ["password1", "password2"]
  console_ssh_menu_ports:
    user: "root"
    passwd: ["password1", "password2"]
