ansible_ssh_pass: password
ansible_become_pass: password
sonicadmin_user: admin
sonicadmin_password: password
sonicadmin_initial_password: password

console_login:
  console_telnet:
    user: "root"
    passwd: ["password1", "password2"]
  console_ssh:
    user: "root"
    passwd: ["password1", "password2"]
  console_ssh_menu_ports:
    user: "root"
    passwd: ["password1", "password2"]
