---
#starlab (str) group variables
# file: group_vars/str.yml

# ntp variables
ntp_servers: ['10.20.8.129', '10.20.8.130']

# syslog variables
syslog_servers: ['10.64.246.95']

# dns variables
dns_servers: ['10.3.145.98', '10.3.145.99', '10.65.5.5']

# forced_mgmt_routes
# 40.122.216.24 acsdockerregistry.blob.core.windows.net
# 13.91.48.226 apt-mo.trafficmanager.net
# 10.3.145.14 lab tacacs server
# 10.3.145.98/31 lab proxy
forced_mgmt_routes: ['10.3.145.98/31', '10.3.145.8', '100.127.20.16/28', '10.3.149.170/31', '40.122.216.24', '13.91.48.226', '10.3.145.14', '10.64.246.0/23', '10.64.5.5', '10.201.148.32/28']

#properties of ErspanDestinationIpv4 in minigraph
erspan_dest: ['10.20.6.16']

#'RadiusResources' in minigraph
radius_servers: []

# TACACS server used by lab only, not used in tests or minigraph
lab_tacacs_servers: ['10.3.145.14', '10.3.145.15']

#'TacacsServer' in minigraph
tacacs_servers: ['100.127.20.21']

#'TacacsGroup' in minigraph
tacacs_group: 'Starlab'

# tacacs facts required for pytest
tacacs_passkey: testing123

#'SnmpResources in minigraph
snmp_servers: ['10.3.145.98']

#'DhcpResources' in minigraph
dhcp_servers: ['192.0.0.1', '192.0.0.2', '192.0.0.3', '192.0.0.4', '192.0.0.5', '192.0.0.6', '192.0.0.7', '192.0.0.8', '192.0.0.9', '192.0.0.10', '192.0.0.11', '192.0.0.12', '192.0.0.13', '192.0.0.14', '192.0.0.15', '192.0.0.16', '192.0.0.17', '192.0.0.18', '192.0.0.19', '192.0.0.20', '192.0.0.21', '192.0.0.22', '192.0.0.23', '192.0.0.24', '192.0.0.25', '192.0.0.26', '192.0.0.27', '192.0.0.28', '192.0.0.29', '192.0.0.30', '192.0.0.31', '192.0.0.32', '192.0.0.33', '192.0.0.34', '192.0.0.35', '192.0.0.36', '192.0.0.37', '192.0.0.38', '192.0.0.39', '192.0.0.40', '192.0.0.41', '192.0.0.42', '192.0.0.43', '192.0.0.44', '192.0.0.45', '192.0.0.46', '192.0.0.47', '192.0.0.48']
dhcpv6_servers: ['fc02:2000::1', 'fc02:2000::2', 'fc02:2000::3', 'fc02:2000::4']

# snmp variables
snmp_rocommunity: msft
snmp_location: str

# NetworkDeviceManager SLB VIP
ndm_vip: 25.71.6.196

#Active Directory Integration
ad_integration_enabled: True

# OU for this environment (TEST,PREPRODUCTION,PRODUCTION)
ou_environment: TEST

#network security groups
ad_domain: GME
rw_netgroups: [
        "NWK-FABRIC-FTE-ALLDVC-PERSISTENTRW",          # FTEs with full time RW for FABRIC devices; they do not use JIT for access
        "NWK-FABRIC-FTE-ALLDVC-TEMPRW",                # FTEs allowed to use JIT to request elevation of access to FABRIC devices
        "NWK-FABRIC-VENDOR-ALLDVC-TEMPRW",             # Vendors allowed to use JIT to request elevation of access to FABRIC devices
        "NWK-AZURE-FABRICATOR-TORTEST-CUSTOM",         # starlab test users
]

ro_netgroups: [
        "NWK-ALLDVC-PERSISTENTRO",                     # users with full time RO access to all network devices
]

# bgp slb passive range
bgp_slb_passive_range: 10.255.0.0/25

#TBD for ACS-MSN2700 xon_1, xon_2:
# Once the new fw version with the fix is burned, should change the
# xon_th_pkts to 10687
# xoff_th_pkts to 0
# since xon_th and xoff_th are configured to the same value.
# The current parameters are according to current fw behavior
qos_params:
    ACS-MSN2700:
        xoff_1:
            dscp: 3
            ecn: 0
            xoff_th_pkts: 10653
            fill_buffer_pkts: 158
            pg: 3
        xoff_2:
            dscp: 4
            ecn: 0
            xoff_th_pkts: 10653
            fill_buffer_pkts: 158
            pg: 4
        xon_1:
            dscp: 3
            ecn: 0
            xon_th_pkts: 185
            xoff_th_pkts: 10468
            pg: 3
        xon_2:
            dscp: 4
            ecn: 0
            xon_th_pkts: 185
            xoff_th_pkts: 10468
            pg: 4
        ecn_1:
            dscp: 8
            ecn: 0
            num_of_pkts: 5000
            limit: 182000
            min_limit: 180000
            cell_size: 96
        ecn_2:
            dscp: 8
            ecn: 1
            num_of_pkts: 2047
            limit: 182320
            min_limit: 0
            cell_size: 96
        ecn_3:
            dscp: 0
            ecn: 0
            num_of_pkts: 5000
            limit: 182000
            min_limit: 180000
            cell_size: 96
        ecn_4:
            dscp: 0
            ecn: 1
            num_of_pkts: 2047
            limit: 182320
            min_limit: 0
            cell_size: 96
        lossy_queue:
            dscp: 8
            ecn: 1
            num_of_pkts: 28676
        wrr:
           dscp: 8
           ecn: 1
           q0_num_of_pkts: 600
           q1_num_of_pkts: 400
           q3_num_of_pkts: 500
           q4_num_of_pkts: 500
           limit: 80
