name: NightlyTest_$(Build.DefinitionName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none


schedules:
  - cron: "0 12 * * *"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

resources:
  repositories:
    - repository: sonic-mgmt
      type: github
      name: sonic-net/sonic-mgmt
      ref: master
      endpoint: sonic-net

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: "testbed-str-e1031-acs-1, testbed-bjw-can-e1031-1"
    displayName: "Testbed Name"

  - name: MIN_WORKER
    type: string
    default: "1"

  - name: MAX_WORKER
    type: string
    default: "2"

  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_202305_SLIM)
    displayName: "Image URL"

  - name: MGMT_BRANCH
    type: string
    default: internal-202305

  # Custom run scripts, if both SCRIPTS and FEATURES are empty, all the test will be executed
  - name: SCRIPTS
    type: string
    default: " "
    displayName: "Scripts to be included"

  - name: FEATURES
    type: string
    default: " "
    displayName: "Features to be included"

  # Custom skip scripts
  - name: SCRIPTS_EXCLUDE
    type: string
    default: "acl/test_stress_acl.py, \
              disk/test_disk_exhaustion.py, \
              dut_console/test_console_baud_rate.py, \
              platform_tests/link_flap/test_cont_link_flap.py, \
              platform_tests/link_flap/test_link_flap.py, \
              platform_tests/test_memory_exhaustion.py, \
              stress/test_stress_routes.py, \
              tacacs/test_ro_disk.py, \
              show_techsupport/test_auto_techsupport.py"
    displayName: "Scripts to be excluded"

  - name: FEATURES_EXCLUDE
    type: string
    default: "everflow,gnmi,generic_config_updater"
    displayName: "Features to be excluded"

  - name: SPECIFIC_PARAM
    type: string
    default: '[
      {"name": "copp/test_copp.py", "param": "--deselect=copp/test_copp.py::TestCOPP::test_add_new_trap --deselect=copp/test_copp.py::TestCOPP::test_remove_trap --deselect=copp/test_copp.py::TestCOPP::test_trap_config_save_after_reboot"},
      {"name": "platform_tests/sfp/test_sfputil.py", "param": "--deselect=platform_tests/sfp/test_sfputil.py::test_check_sfputil_error_status"},
      {"name": "platform_tests/test_reboot.py", "param": "--deselect=platform_tests/test_reboot.py::test_watchdog_reboot"}
    ]'
    displayName: "Specific param, support feature(e.g. 'bgp') or test module(e.g. 'bgp/test_bgp_fact.py')"

  - name: COMMON_EXTRA_PARAMS
    type: string
    default: "--topology m0,any --no_dscp_uniform --py_saithrift_url=$(SAITHRIFT_BRCM_202012)"
    displayName: "Common test parameters"

  - name: AFFINITY
    type: string
    # For the 2 dut_console test modules, they cannot pass on testbed-str-e1031-acs-1 due to console server issue.
    default: '[
      {"name": "dut_console/test_escape_character.py", "op": "NOT_ON", "value": ["testbed-str-e1031-acs-1"]},
      {"name": "dut_console/test_idle_timeout.py", "op": "NOT_ON", "value": ["testbed-str-e1031-acs-1"]}
    ]'
    displayName: "Test affinity, only support test module(e.g. 'bgp/test_bgp_fact.py')"

  # Test timeout
  - name: MAX_RUN_TEST_MINUTES
    type: number
    default: 1380  # 23 hours

stages:
- stage: Test

  variables:
    - group: SONiC-Elastictest

  jobs:
  - job:
    displayName: e1031.m0.202305.NightlyTest_by_Elastictest
    timeoutInMinutes: ${{ parameters.MAX_RUN_TEST_MINUTES }}
    continueOnError: false
    pool: sonic-ubuntu-1c
    steps:
    - template: ../../run-test-nightly-elastictest-template.yml
      parameters:
        TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
        SCRIPTS: ${{ parameters.SCRIPTS }}
        FEATURES: ${{ parameters.FEATURES }}
        SCRIPTS_EXCLUDE: ${{ parameters.SCRIPTS_EXCLUDE }}
        FEATURES_EXCLUDE: ${{ parameters.FEATURES_EXCLUDE }}
        SPECIFIC_PARAM: ${{ parameters.SPECIFIC_PARAM }}
        COMMON_EXTRA_PARAMS: ${{ parameters.COMMON_EXTRA_PARAMS }}
        AFFINITY: ${{ parameters.AFFINITY }}
        MGMT_BRANCH: ${{ parameters.MGMT_BRANCH }}
        MAX_RUN_TEST_MINUTES: ${{ parameters.MAX_RUN_TEST_MINUTES }}
        IMAGE_URL: ${{ parameters.IMAGE_URL }}
        MIN_WORKER: ${{ parameters.MIN_WORKER }}
        MAX_WORKER: ${{ parameters.MAX_WORKER }}
