---
# The user/password you give to server in initialization
init_user: use_own_value
init_password: use_own_value
init_sudo_pass: use_own_value

# Server credential
server_user: "{{ secret_group_vars['vm_host']['ansible_user'] }}"
server_password: "{{ secret_group_vars['vm_host']['ansible_password'] }}"

ansible_connection: multi_passwd_ssh
ansible_altpasswords: "{{ secret_group_vars['vm_host']['altpasswords'] }}"
