mgmt_bridge: br1
mgmt_prefixlen: 17
mgmt_gw: 10.150.22.1
external_port: ens4f1
mgmt_bridge_addresses:
 - "10.150.22.245/23"
 - "172.16.210.5/17"

proxy_env:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
