mgmt_bridge: br1
mgmt_gw: 10.255.0.1
external_iface: p4p1


ptf_1_enabled: true
ptf_1_mgmt_ip: 10.255.0.188/24
ptf_1_vlan_base: 393

ptf_2_enabled: false
ptf_2_mgmt_ip: 10.255.0.50/24
ptf_2_vlan_base: 101 # ???

ptf_3_enabled: true
ptf_3_mgmt_ip: 10.255.0.254/24
ptf_3_vlan_base: 233

ptf_4_enabled: true
ptf_4_mgmt_ip: 10.255.0.185/24
ptf_4_vlan_base: 265

ptf_5_enabled: true
ptf_5_mgmt_ip: 10.255.0.176/24
ptf_5_vlan_base: 553

ptf_6_enabled: true
ptf_6_mgmt_ip: 10.255.0.177/24
ptf_6_vlan_base: 425

vm_1_enabled: true
vm_1_vlan_base: 489
vm_1_injected_ip: 10.255.0.178/24
VMs_1:
  ARISTA01T0:
    num: 0
    filename: 01-ARISTA01T0.xml
    serial_port: 5000
    vlans: "16"
    memory: "{{ tor_memory }}"
  ARISTA01T2:
    num: 1
    filename: 01-ARISTA01T2.xml
    serial_port: 5016
    vlans: "0"
    memory: "{{ spine_memory }}"
  ARISTA02T0:
    num: 2
    filename: 01-ARISTA02T0.xml
    serial_port: 5001
    vlans: "17"
    memory: "{{ tor_memory }}"
  ARISTA02T2:
    num: 3
    filename: 01-ARISTA02T2.xml
    serial_port: 5017
    vlans: "1"
    memory: "{{ spine_memory }}"
  ARISTA03T0:
    num: 4
    filename: 01-ARISTA03T0.xml
    serial_port: 5002
    vlans: "18"
    memory: "{{ tor_memory }}"
  ARISTA03T2:
    num: 5
    filename: 01-ARISTA03T2.xml
    serial_port: 5018
    vlans: "2"
    memory: "{{ spine_memory }}"
  ARISTA04T0:
    num: 6
    filename: 01-ARISTA04T0.xml
    serial_port: 5003
    vlans: "19"
    memory: "{{ tor_memory }}"
  ARISTA04T2:
    num: 7
    filename: 01-ARISTA04T2.xml
    serial_port: 5019
    vlans: "3"
    memory: "{{ spine_memory }}"
  ARISTA05T0:
    num: 8
    filename: 01-ARISTA05T0.xml
    serial_port: 5004
    vlans: "20"
    memory: "{{ tor_memory }}"
  ARISTA05T2:
    num: 9
    filename: 01-ARISTA05T2.xml
    serial_port: 5020
    vlans: "4"
    memory: "{{ spine_memory }}"
  ARISTA06T0:
    num: 10
    filename: 01-ARISTA06T0.xml
    serial_port: 5005
    vlans: "21"
    memory: "{{ tor_memory }}"
  ARISTA06T2:
    num: 11
    filename: 01-ARISTA06T2.xml
    serial_port: 5021
    vlans: "5"
    memory: "{{ spine_memory }}"
  ARISTA07T0:
    num: 12
    filename: 01-ARISTA07T0.xml
    serial_port: 5006
    vlans: "22"
    memory: "{{ tor_memory }}"
  ARISTA07T2:
    num: 13
    filename: 01-ARISTA07T2.xml
    serial_port: 5022
    vlans: "6"
    memory: "{{ spine_memory }}"
  ARISTA08T0:
    num: 14
    filename: 01-ARISTA08T0.xml
    serial_port: 5007
    vlans: "23"
    memory: "{{ tor_memory }}"
  ARISTA08T2:
    num: 15
    filename: 01-ARISTA08T2.xml
    serial_port: 5023
    vlans: "7"
    memory: "{{ spine_memory }}"
  ARISTA09T0:
    num: 16
    filename: 01-ARISTA09T0.xml
    serial_port: 5008
    vlans: "24"
    memory: "{{ tor_memory }}"
  ARISTA09T2:
    num: 17
    filename: 01-ARISTA09T2.xml
    serial_port: 5024
    vlans: "8"
    memory: "{{ spine_memory }}"
  ARISTA10T0:
    num: 18
    filename: 01-ARISTA10T0.xml
    serial_port: 5009
    vlans: "25"
    memory: "{{ tor_memory }}"
  ARISTA10T2:
    num: 19
    filename: 01-ARISTA10T2.xml
    serial_port: 5025
    vlans: "9"
    memory: "{{ spine_memory }}"
  ARISTA11T0:
    num: 20
    filename: 01-ARISTA11T0.xml
    serial_port: 5010
    vlans: "26"
    memory: "{{ tor_memory }}"
  ARISTA11T2:
    num: 21
    filename: 01-ARISTA11T2.xml
    serial_port: 5026
    vlans: "10"
    memory: "{{ spine_memory }}"
  ARISTA12T0:
    num: 22
    filename: 01-ARISTA12T0.xml
    serial_port: 5011
    vlans: "27"
    memory: "{{ tor_memory }}"
  ARISTA12T2:
    num: 23
    filename: 01-ARISTA12T2.xml
    serial_port: 5027
    vlans: "11"
    memory: "{{ spine_memory }}"
  ARISTA13T0:
    num: 24
    filename: 01-ARISTA13T0.xml
    serial_port: 5012
    vlans: "28"
    memory: "{{ tor_memory }}"
  ARISTA13T2:
    num: 25
    filename: 01-ARISTA13T2.xml
    serial_port: 5028
    vlans: "12"
    memory: "{{ spine_memory }}"
  ARISTA14T0:
    num: 26
    filename: 01-ARISTA14T0.xml
    serial_port: 5013
    vlans: "29"
    memory: "{{ tor_memory }}"
  ARISTA14T2:
    num: 27
    filename: 01-ARISTA14T2.xml
    serial_port: 5029
    vlans: "13"
    memory: "{{ spine_memory }}"
  ARISTA15T0:
    num: 28
    filename: 01-ARISTA15T0.xml
    serial_port: 5014
    vlans: "30"
    memory: "{{ tor_memory }}"
  ARISTA15T2:
    num: 29
    filename: 01-ARISTA15T2.xml
    serial_port: 5030
    vlans: "14"
    memory: "{{ spine_memory }}"
  ARISTA16T0:
    num: 30
    filename: 01-ARISTA16T0.xml
    serial_port: 5015
    vlans: "31"
    memory: "{{ tor_memory }}"
  ARISTA16T2:
    num: 31
    filename: 01-ARISTA16T2.xml
    serial_port: 5031
    vlans: "15"
    memory: "{{ spine_memory }}"


vm_2_enabled: true
vm_2_vlan_base: 297
vm_2_injected_ip: 10.255.0.179/24
VMs_2:
  ARISTA01T0:
    num: 0
    filename: 03-ARISTA01T0.xml
    serial_port: 5032
    vlans: "16"
    memory: "{{ tor_memory }}"
  ARISTA01T2:
    num: 1
    filename: 03-ARISTA01T2.xml
    serial_port: 5048
    vlans: "0"
    memory: "{{ spine_memory }}"
  ARISTA02T0:
    num: 2
    filename: 03-ARISTA02T0.xml
    serial_port: 5033
    vlans: "17"
    memory: "{{ tor_memory }}"
  ARISTA02T2:
    num: 3
    filename: 03-ARISTA02T2.xml
    serial_port: 5049
    vlans: "1"
    memory: "{{ spine_memory }}"
  ARISTA03T0:
    num: 4
    filename: 03-ARISTA03T0.xml
    serial_port: 5034
    vlans: "18"
    memory: "{{ tor_memory }}"
  ARISTA03T2:
    num: 5
    filename: 03-ARISTA03T2.xml
    serial_port: 5050
    vlans: "2"
    memory: "{{ spine_memory }}"
  ARISTA04T0:
    num: 6
    filename: 03-ARISTA04T0.xml
    serial_port: 5035
    vlans: "19"
    memory: "{{ tor_memory }}"
  ARISTA04T2:
    num: 7
    filename: 03-ARISTA04T2.xml
    serial_port: 5051
    vlans: "3"
    memory: "{{ spine_memory }}"
  ARISTA05T0:
    num: 8
    filename: 03-ARISTA05T0.xml
    serial_port: 5036
    vlans: "20"
    memory: "{{ tor_memory }}"
  ARISTA05T2:
    num: 9
    filename: 03-ARISTA05T2.xml
    serial_port: 5052
    vlans: "4"
    memory: "{{ spine_memory }}"
  ARISTA06T0:
    num: 10
    filename: 03-ARISTA06T0.xml
    serial_port: 5037
    vlans: "21"
    memory: "{{ tor_memory }}"
  ARISTA06T2:
    num: 11
    filename: 03-ARISTA06T2.xml
    serial_port: 5053
    vlans: "5"
    memory: "{{ spine_memory }}"
  ARISTA07T0:
    num: 12
    filename: 03-ARISTA07T0.xml
    serial_port: 5038
    vlans: "22"
    memory: "{{ tor_memory }}"
  ARISTA07T2:
    num: 13
    filename: 03-ARISTA07T2.xml
    serial_port: 5054
    vlans: "6"
    memory: "{{ spine_memory }}"
  ARISTA08T0:
    num: 14
    filename: 03-ARISTA08T0.xml
    serial_port: 5039
    vlans: "23"
    memory: "{{ tor_memory }}"
  ARISTA08T2:
    num: 15
    filename: 03-ARISTA08T2.xml
    serial_port: 5055
    vlans: "7"
    memory: "{{ spine_memory }}"
  ARISTA09T0:
    num: 16
    filename: 03-ARISTA09T0.xml
    serial_port: 5040
    vlans: "24"
    memory: "{{ tor_memory }}"
  ARISTA09T2:
    num: 17
    filename: 03-ARISTA09T2.xml
    serial_port: 5056
    vlans: "8"
    memory: "{{ spine_memory }}"
  ARISTA10T0:
    num: 18
    filename: 03-ARISTA10T0.xml
    serial_port: 5041
    vlans: "25"
    memory: "{{ tor_memory }}"
  ARISTA10T2:
    num: 19
    filename: 03-ARISTA10T2.xml
    serial_port: 5057
    vlans: "9"
    memory: "{{ spine_memory }}"
  ARISTA11T0:
    num: 20
    filename: 03-ARISTA11T0.xml
    serial_port: 5042
    vlans: "26"
    memory: "{{ tor_memory }}"
  ARISTA11T2:
    num: 21
    filename: 03-ARISTA11T2.xml
    serial_port: 5058
    vlans: "10"
    memory: "{{ spine_memory }}"
  ARISTA12T0:
    num: 22
    filename: 03-ARISTA12T0.xml
    serial_port: 5043
    vlans: "27"
    memory: "{{ tor_memory }}"
  ARISTA12T2:
    num: 23
    filename: 03-ARISTA12T2.xml
    serial_port: 5059
    vlans: "11"
    memory: "{{ spine_memory }}"
  ARISTA13T0:
    num: 24
    filename: 03-ARISTA13T0.xml
    serial_port: 5044
    vlans: "28"
    memory: "{{ tor_memory }}"
  ARISTA13T2:
    num: 25
    filename: 03-ARISTA13T2.xml
    serial_port: 5060
    vlans: "12"
    memory: "{{ spine_memory }}"
  ARISTA14T0:
    num: 26
    filename: 03-ARISTA14T0.xml
    serial_port: 5045
    vlans: "29"
    memory: "{{ tor_memory }}"
  ARISTA14T2:
    num: 27
    filename: 03-ARISTA14T2.xml
    serial_port: 5061
    vlans: "13"
    memory: "{{ spine_memory }}"
  ARISTA15T0:
    num: 28
    filename: 03-ARISTA15T0.xml
    serial_port: 5046
    vlans: "30"
    memory: "{{ tor_memory }}"
  ARISTA15T2:
    num: 29
    filename: 03-ARISTA15T2.xml
    serial_port: 5062
    vlans: "14"
    memory: "{{ spine_memory }}"
  ARISTA16T0:
    num: 30
    filename: 03-ARISTA16T0.xml
    serial_port: 5047
    vlans: "31"
    memory: "{{ tor_memory }}"
  ARISTA16T2:
    num: 31
    filename: 03-ARISTA16T2.xml
    serial_port: 5063
    vlans: "15"
    memory: "{{ spine_memory }}"

