mgmt_bridge: br1
mgmt_prefixlen: 19
mgmt_intf_name: eno8303
mgmt_gw: 10.64.247.1
mgmt_gw_v6: 2a01:111:e210:b000::a40:f701
vm_mgmt_gw: 172.16.128.1
external_port: ens55f0
mgmt_bridge_addresses:
 - "172.16.228.5/17"

proxy_env:
  http_proxy: "http://10.201.148.40:8080"
  https_proxy: "http://10.201.148.40:8080"
  no_proxy: "localhost,127.0.0.0,127.0.1.1"
