---
    # Public graph files
    - lab_connection_graph.xml
    - example_ixia_connection_graph.xml


    # Private graph files
    - starlab_connection_graph.xml
    - spytest_connection_graph.xml
    - svctest_connection_graph.xml
    - ixia_connection_graph.xml
