name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 16 * * 2,4"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal-202205
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: testbed-bjw-can-7050qx-1
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(BJW_IMAGE_BRCM_ABOOT_202205_SLIM)
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(BJW_SAITHRIFT_BRCM_202205)
    displayName: "py_saithrift URL"

  # Testbed specific, to skip and/or include directories
  - name: TESTBED_SPECIFIC
    type: string
    default: '-I "copp qos"'
    displayName: Testbed specific

  # Test timeout
  - name: NIGHTLY_TEST_TIMEOUT
    type: number
    default: 600

  - name: AGENT_POOL
    type: string
    default: nightly-bjw
    displayName: "Agent pool"

  - name: PREV_IMAGE_URL
    type: string
    default: $(BJW_IMAGE_BRCM_ABOOT_201811)
    displayName: "Previous Image URL"

  - name: DOCKER_FOLDER_SIZE
    type: string
    default: 3000M
    displayName: "docker folder size when docker_inram enabled"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      TESTBED_SPECIFIC: ${{ parameters.TESTBED_SPECIFIC }}
      NIGHTLY_TEST_TIMEOUT: ${{ parameters.NIGHTLY_TEST_TIMEOUT }}
      AGENT_POOL: ${{ parameters.AGENT_POOL }}
      PREV_IMAGE_URL: ${{ parameters.PREV_IMAGE_URL }}
      DOCKER_FOLDER_SIZE: ${{ parameters.DOCKER_FOLDER_SIZE }}
