name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "1 12 * * 6"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal-202205
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: testbed-str2-pikez-acs-1
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_ABOOT_202205)
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_BRCM_202205)
    displayName: "py_saithrift URL"

  - name: EXTRA_PARAMS
    type: string
    default: "--no_dscp_uniform"
    displayName: "Extra pytest params"

  - name: SKIP_SCRIPTS
    type: string
    default: "platform_tests/link_flap/test_cont_link_flap.py \
              platform_tests/test_power_off_reboot.py"
    displayName: "Skip Scripts"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      EXTRA_PARAMS: ${{ parameters.EXTRA_PARAMS }}
      SKIP_SCRIPTS: ${{ parameters.SKIP_SCRIPTS }}
