name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

resources:
  repositories:
  - repository: https://mssonic@dev.azure.com/mssonic/internal/_git/sonic-metadata
    type: git
    name: sonic-metadata
    ref: master

schedules:
  - cron: "30 10 * * 0,2,4"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal-202012
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: testbed-bjw-can-7050qx-2
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(BJW_IMAGE_BRCM_ABOOT_202012_SLIM)
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(BJW_SAITHRIFT_BRCM_202012)
    displayName: "py_saithrift URL"

  # Testbed specific, to skip and/or include directories
  - name: TESTBED_SPECIFIC
    type: string
    default: '-I "platform_tests copp show_techport acl everflow drop_packets"'
    displayName: Testbed specific

  # Custom skip scripts
  - name: SKIP_SCRIPTS
    type: string
    default: ""
    displayName: "Skip Scripts"

  # Test timeout
  - name: NIGHTLY_TEST_TIMEOUT
    type: number
    default: 1800

  - name: AGENT_POOL
    type: string
    default: nightly-bjw
    displayName: "Agent pool"

  - name: PREV_IMAGE_URL
    type: string
    default: $(BJW_IMAGE_BRCM_ABOOT_201811)
    displayName: "Previous Image URL"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      TESTBED_SPECIFIC: ${{ parameters.TESTBED_SPECIFIC }}
      SKIP_SCRIPTS: ${{ parameters.SKIP_SCRIPTS }}
      NIGHTLY_TEST_TIMEOUT: ${{ parameters.NIGHTLY_TEST_TIMEOUT }}
      AGENT_POOL: ${{ parameters.AGENT_POOL }}
      PREV_IMAGE_URL: ${{ parameters.PREV_IMAGE_URL }}
