name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 4 * * 1,3"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms24-t0-7260-2
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_ABOOT_INTERNAL)
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_BRCM_INTERNAL)
    displayName: "py_saithrift URL"

  # Testbed specific, to skip and/or include directories
  - name: TESTBED_SPECIFIC
    type: string
    default: '-I "platform_tests qos"'
    displayName: Testbed specific

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      TESTBED_SPECIFIC: ${{ parameters.TESTBED_SPECIFIC }}
