name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

# run on internal or private image
schedules:
  - cron: "0 18 * * FRI"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
        - arlakshm/internal/arista_chassis_topo
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms6-t1-7060
    displayName: "Testbed Name"

  # Upgrade parameters
  # for now ignore updating the images on chassis
  - name: IMAGE_URL
    type: string
    default: ""
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_BRCM_201911)
    displayName: "py_saithrift URL"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
