
parameters:
- name: SERVICE_CONNECTION
  type: string
  default: ""

steps:

  - task: AzureCLI@2
    inputs:
      azureSubscription: ${{ parameters.SERVICE_CONNECTION }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        pwd

        accessToken=$(az account get-access-token --query accessToken -o tsv)
        echo "##vso[task.setvariable variable=ACCESS_TOKEN;issecret=true]$accessToken  "

    displayName: Get ACCESS_TOKEN
