name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 4 * * 0,1,3,5"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms18-t1-msn4600c-acs-1
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_MLNX_202305)
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_MLNX_202305)
    displayName: "py_saithrift URL"

  # Testbed specific, to skip and/or include directories
  - name: TESTBED_SPECIFIC
    type: string
    default: '-S ""'
    displayName: Testbed specific

  # Custom skip scripts
  - name: SKIP_SCRIPTS
    type: string
    default: "platform_tests/test_auto_negotiation.py"
    displayName: "Skip Scripts"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      TESTBED_SPECIFIC: ${{ parameters.TESTBED_SPECIFIC }}
      SKIP_SCRIPTS: ${{ parameters.SKIP_SCRIPTS }}
