name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 14 * * 0-5"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms7-t0-4600c-2
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_MLNX_202012)
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_MLNX_202012)
    displayName: "py_saithrift URL"

  # Test timeout
  - name: NIGHTLY_TEST_TIMEOUT
    type: number
    default: 1920    # minutes, totally 32 hours

  - name: SKIP_SCRIPTS
    type: string
    default: "vrf/test_vrf.py vrf/test_vrf_attr.py"
    displayName: "Skip Scripts"

  # Split platform_tests into another testbed
  - name: TESTBED_SPECIFIC
    type: string
    default: '-S "platform_tests"'
    displayName: Testbed specific
stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      NIGHTLY_TEST_TIMEOUT: ${{ parameters.NIGHTLY_TEST_TIMEOUT }}
      SKIP_SCRIPTS: ${{ parameters.SKIP_SCRIPTS }}
      TESTBED_SPECIFIC: ${{ parameters.TESTBED_SPECIFIC }}
