name: NightlyTest_$(Build.DefinitionName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none


schedules:
  - cron: "0 10 * * 5"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

resources:
  repositories:
    - repository: sonic-mgmt
      type: github
      name: sonic-net/sonic-mgmt
      ref: master
      endpoint: sonic-net

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS


parameters:
  - name: TESTBED_NAME
    type: string
    default: "vms64-t1-s6100-1, vms68-t1-s6100-1, tbtk5-t1-s6100-5"
    displayName: "Testbed Name"

  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_PUBLIC)
    displayName: "Image URL"

  - name: UPGRADE_IMAGE_PARAM
    type: string
    default: "--always-power-cycle=True"
    displayName: "Upgrade image parameter"

  - name: MGMT_BRANCH
    type: string
    default: internal

  # Custom run scripts, if both SCRIPTS and FEATURES are empty, all the test will be executed
  - name: SCRIPTS
    type: string
    default: " "
    displayName: "Scripts to be executed"

  - name: FEATURES
    type: string
    default: " "
    displayName: "Features to be executed"

  # Custom skip scripts
  - name: SCRIPTS_EXCLUDE
    type: string
    default: " "
    displayName: "Scripts to be excluded"

  - name: FEATURES_EXCLUDE
    type: string
    default: "pfc_asym, span, sub_port_interfaces"
    displayName: "Features to be excluded"

  - name: COMMON_EXTRA_PARAMS
    type: string
    default: "--topology t1,any --py_saithrift_url=$(SAITHRIFT_BRCM_PUBLIC)"
    displayName: "Common test parameters"

  - name: SPECIFIC_PARAM
    type: string
    default: '[
    {"name": "qos", "param": "--public_docker_registry"}
    ]'
    displayName: "Specific param, support feature(e.g. 'bgp') or test module(e.g. 'bgp/test_bgp_fact.py')"

  # Test timeout
  - name: MAX_RUN_TEST_MINUTES
    type: number
    default: 3600

stages:
- stage: Test

  variables:
    - group: SONiC-Elastictest

  jobs:
  - job:
    displayName: 6100.t1.master.NightlyTest_by_Elastictest
    timeoutInMinutes: ${{ parameters.MAX_RUN_TEST_MINUTES }}
    continueOnError: false
    pool: sonic-ubuntu-1c
    steps:
    - template: ../../run-test-nightly-elastictest-template.yml
      parameters:
        TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
        SCRIPTS: ${{ parameters.SCRIPTS }}
        FEATURES: ${{ parameters.FEATURES }}
        SCRIPTS_EXCLUDE: ${{ parameters.SCRIPTS_EXCLUDE }}
        FEATURES_EXCLUDE: ${{ parameters.FEATURES_EXCLUDE }}
        COMMON_EXTRA_PARAMS: ${{ parameters.COMMON_EXTRA_PARAMS }}
        SPECIFIC_PARAM: ${{ parameters.SPECIFIC_PARAM }}
        MGMT_BRANCH: ${{ parameters.MGMT_BRANCH }}
        MAX_RUN_TEST_MINUTES: ${{ parameters.MAX_RUN_TEST_MINUTES }}
        IMAGE_URL: ${{ parameters.IMAGE_URL }}
        UPGRADE_IMAGE_PARAM: ${{ parameters.UPGRADE_IMAGE_PARAM }}
