topology:
  host_interfaces:
   - 2
   - 3
   - 6
   - 7
   - 8
   - 9
   - 10
   - 11
   - 12
   - 13
   - 14
   - 15
   - 18
   - 19
   - 22
   - 23
   - 24
   - 25
   - 26
   - 27
   - 28
   - 29
   - 30
   - 31
  VMs:
    ARISTA01T1:
      vlans:
        - 0
        - 1
      vm_offset: 0
    ARISTA02T1:
      vlans:
        - 4
        - 5
      vm_offset: 1
    ARISTA03T1:
      vlans:
        - 16
        - 17
      vm_offset: 2
    ARISTA04T1:
      vlans:
        - 20
        - 21
      vm_offset: 3
  DUT:
    vlan_configs:
      default_vlan_config: one_vlan_a
      one_vlan_a:
        Vlan1000:
          id: 1000
          intfs: [2, 3, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 19, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
          prefix: 192.168.0.1/21
          prefix_v6: fc02:1000::1/64
          tag: 1000
      two_vlan_a:
        Vlan100: 
          id: 100
          intfs: [2, 3, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
          prefix: 192.168.0.1/22
          prefix_v6: fc02:100::1/64
          tag: 100
        Vlan200: 
          id: 200
          intfs: [18, 19, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
          prefix: 192.168.4.1/22
          prefix_v6: fc02:200::1/64
          tag: 200

configuration_properties:
  common:
    dut_asn: 64601
    dut_type: ToRRouter
    swrole: leaf
    podset_number: 200
    tor_number: 16
    tor_subnet_number: 2
    max_tor_subnet_number: 16
    tor_subnet_size: 128
    spine_asn: 65534
    leaf_asn_start: 64802
    tor_asn_start: 64601
    failure_rate: 0
    nhipv4: 10.10.246.254
    nhipv6: FC0A::FF

configuration:
  ARISTA01T1:
    properties:
    - common
    bgp:
      asn: 64802
      peers:
        64601:
        - 10.0.0.0
        - FC00::1
    interfaces:
      Loopback0:
        ipv4: 100.1.0.1/32
        ipv6: 2064:100::1/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.1/31
        ipv6: fc00::2/126
    bp_interface:
      ipv4: 10.10.246.1/24
      ipv6: fc0a::1/64

  ARISTA02T1:
    properties:
    - common
    bgp:
      asn: 64802
      peers:
        64601:
        - 10.0.0.4
        - FC00::9
    interfaces:
      Loopback0:
        ipv4: 100.1.0.2/32
        ipv6: 2064:100::2/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.5/31
        ipv6: fc00::a/126
    bp_interface:
      ipv4: 10.10.246.2/24
      ipv6: fc0a::2/64

  ARISTA03T1:
    properties:
    - common
    bgp:
      asn: 64802
      peers:
        64601:
        - 10.0.0.8
        - FC00::11
    interfaces:
      Loopback0:
        ipv4: 100.1.0.3/32
        ipv6: 2064:100::3/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.9/31
        ipv6: fc00::12/126
    bp_interface:
      ipv4: 10.10.246.3/24
      ipv6: fc0a::3/64

  ARISTA04T1:
    properties:
    - common
    bgp:
      asn: 64802
      peers:
        64601:
        - 10.0.0.12
        - FC00::19
    interfaces:
      Loopback0:
        ipv4: 100.1.0.4/32
        ipv6: 2064:100::4/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.13/31
        ipv6: fc00::1a/126
    bp_interface:
      ipv4: 10.10.246.4/24
      ipv6: fc0a::4/64
