topology:
  VMs:
    ARISTA01T3:
      vlans:
        - 0
      vm_offset: 0
    ARISTA02LT2:
      vlans:
        - 1
      vm_offset: 1
    ARISTA03T3:
      vlans:
        - 2
      vm_offset: 2
    ARISTA04LT2:
      vlans:
        - 3
      vm_offset: 3
    ARISTA05T3:
      vlans:
        - 4
        - 6
        - 8
        - 10
      vm_offset: 4
    ARISTA06LT2:
      vlans:
        - 5
      vm_offset: 5
    ARISTA07LT2:
      vlans:
        - 7
      vm_offset: 6
    ARISTA08LT2:
      vlans:
        - 9
      vm_offset: 7
    ARISTA09LT2:
      vlans:
        - 11
      vm_offset: 8
    ARISTA10T3:
      vlans:
        - 12
      vm_offset: 9
    ARISTA11LT2:
      vlans:
        - 13
      vm_offset: 10
    ARISTA12T3:
      vlans:
        - 14
      vm_offset: 11
    ARISTA13LT2:
      vlans:
        - 15
      vm_offset: 12
    ARISTA14T3:
      vlans:
        - 16
      vm_offset: 13
    ARISTA15LT2:
      vlans:
        - 17
      vm_offset: 14
    ARISTA16T3:
      vlans:
        - 18
      vm_offset: 15
    ARISTA17LT2:
      vlans:
        - 19
      vm_offset: 16
    ARISTA18T3:
      vlans:
        - 20
        - 22
        - 24
        - 26
      vm_offset: 17
    ARISTA19LT2:
      vlans:
        - 21
      vm_offset: 18
    ARISTA20LT2:
      vlans:
        - 23
      vm_offset: 19
    ARISTA21LT2:
      vlans:
        - 25
      vm_offset: 20
    ARISTA22LT2:
      vlans:
        - 27
      vm_offset: 21
    ARISTA23T3:
      vlans:
        - 28
      vm_offset: 22
    ARISTA24LT2:
      vlans:
        - 29
      vm_offset: 23
    ARISTA25T3:
      vlans:
        - 30
      vm_offset: 24
    ARISTA26LT2:
      vlans:
        - 31
      vm_offset: 25

  DUT:
    loopback:
      ipv4:
        - 10.1.0.1/32
      ipv6:
        - FC00:10::1/128

configuration_properties:
  common:
    podset_number: 400
    tor_number: 16
    tor_subnet_number: 8
    max_tor_subnet_number: 32
    tor_subnet_size: 128
    dut_asn: 66000
    dut_confed_asn: 65100
    dut_config_peers: 65200
    dut_type: UpperSpineRouter
    nhipv4: 10.10.246.254
    nhipv6: FC0A::FF
  core:
    swrole: core
  leaf:
    swrole: leaf

configuration:
  ARISTA01T3:
    properties:
      - common
      - core
    bgp:
      peer_in_bgp_confed: true
      asn: 65200
      peers:
        65100:
          - 10.0.0.0
          - FC00::1
    interfaces:
      Loopback0:
        ipv4: 100.1.0.1/32
        ipv6: 2064:100::1/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.1/31
        ipv6: FC00::2/126
    bp_interface:
      ipv4: 10.10.246.1/24
      ipv6: fc0a::2/64
  ARISTA02LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.98
          - fc00::c9
    interfaces:
      Loopback0:
        ipv4: 100.1.0.52/32
        ipv6: 2064:100::32/128
      Ethernet1:
        ipv4: 10.0.0.99/31
        ipv6: fc00::ca/126
    bp_interface:
      ipv4: 10.10.246.101/24
      ipv6: fc0a::64/64
  ARISTA03T3:
    properties:
      - common
      - core
    bgp:
      peer_in_bgp_confed: true
      asn: 65200
      peers:
        65100:
          - 10.0.0.2
          - FC00::5
    interfaces:
      Loopback0:
        ipv4: 100.1.0.2/32
        ipv6: 2064:100::2/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.3/31
        ipv6: FC00::6/126
    bp_interface:
      ipv4: 10.10.246.2/24
      ipv6: fc0a::4/64
  ARISTA04LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.100
          - fc00::cd
    interfaces:
      Loopback0:
        ipv4: 100.1.0.53/32
        ipv6: 2064:100::33/128
      Ethernet1:
        ipv4: 10.0.0.101/31
        ipv6: fc00::ce/126
    bp_interface:
      ipv4: 10.10.246.103/24
      ipv6: fc0a::66/64
  ARISTA05T3:
    properties:
      - common
      - core
    bgp:
      peer_in_bgp_confed: true
      asn: 65200
      peers:
        65100:
          - 10.0.0.4
          - FC00::9
    interfaces:
      Loopback0:
        ipv4: 100.1.0.3/32
        ipv6: 2064:100::3/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Ethernet3:
        lacp: 1
      Ethernet4:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.5/31
        ipv6: FC00::a/126
    bp_interface:
      ipv4: 10.10.246.3/24
      ipv6: fc0a::6/64
  ARISTA06LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.104
          - fc00::d5
    interfaces:
      Loopback0:
        ipv4: 100.1.0.55/32
        ipv6: 2064:100::35/128
      Ethernet1:
        ipv4: 10.0.0.105/31
        ipv6: fc00::d6/126
    bp_interface:
      ipv4: 10.10.246.107/24
      ipv6: fc0a::6a/64
  ARISTA07LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.108
          - fc00::dd
    interfaces:
      Loopback0:
        ipv4: 100.1.0.57/32
        ipv6: 2064:100::37/128
      Ethernet1:
        ipv4: 10.0.0.109/31
        ipv6: fc00::de/126
    bp_interface:
      ipv4: 10.10.246.111/24
      ipv6: fc0a::6e/64
  ARISTA08LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.112
          - fc00::e5
    interfaces:
      Loopback0:
        ipv4: 100.1.0.59/32
        ipv6: 2064:100::39/128
      Ethernet1:
        ipv4: 10.0.0.113/31
        ipv6: fc00::e6/126
    bp_interface:
      ipv4: 10.10.246.115/24
      ipv6: fc0a::72/64
  ARISTA09LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.116
          - fc00::ed
    interfaces:
      Loopback0:
        ipv4: 100.1.0.61/32
        ipv6: 2064:100::3b/128
      Ethernet1:
        ipv4: 10.0.0.117/31
        ipv6: fc00::ee/126
    bp_interface:
      ipv4: 10.10.246.119/24
      ipv6: fc0a::76/64
  ARISTA10T3:
    properties:
      - common
      - core
    bgp:
      peer_in_bgp_confed: true
      asn: 65200
      peers:
        65100:
          - 10.0.0.6
          - FC00::d
    interfaces:
      Loopback0:
        ipv4: 100.1.0.5/32
        ipv6: 2064:100::5/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.7/31
        ipv6: FC00::e/126
    bp_interface:
      ipv4: 10.10.246.5/24
      ipv6: fc0a::8/64
  ARISTA11LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.118
          - fc00::f1
    interfaces:
      Loopback0:
        ipv4: 100.1.0.62/32
        ipv6: 2064:100::3c/128
      Ethernet1:
        ipv4: 10.0.0.119/31
        ipv6: fc00::f2/126
    bp_interface:
      ipv4: 10.10.246.120/24
      ipv6: fc0a::78/64
  ARISTA12T3:
    properties:
      - common
      - core
    bgp:
      peer_in_bgp_confed: true
      asn: 65200
      peers:
        65100:
          - 10.0.0.8
          - FC00::11
    interfaces:
      Loopback0:
        ipv4: 100.1.0.6/32
        ipv6: 2064:100::6/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.9/31
        ipv6: FC00::12/126
    bp_interface:
      ipv4: 10.10.246.6/24
      ipv6: fc0a::a/64
  ARISTA13LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.120
          - fc00::f5
    interfaces:
      Loopback0:
        ipv4: 100.1.0.63/32
        ipv6: 2064:100::3d/128
      Ethernet1:
        ipv4: 10.0.0.121/31
        ipv6: fc00::f6/126
    bp_interface:
      ipv4: 10.10.246.121/24
      ipv6: fc0a::7a/64
  ARISTA14T3:
    properties:
      - common
      - core
    bgp:
      peer_in_bgp_confed: true
      asn: 65200
      peers:
        65100:
          - 10.0.0.10
          - FC00::15
    interfaces:
      Loopback0:
        ipv4: 100.1.0.7/32
        ipv6: 2064:100::7/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.11/31
        ipv6: FC00::16/126
    bp_interface:
      ipv4: 10.10.246.7/24
      ipv6: fc0a::c/64
  ARISTA15LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.122
          - fc00::f9
    interfaces:
      Loopback0:
        ipv4: 100.1.0.64/32
        ipv6: 2064:100::3e/128
      Ethernet1:
        ipv4: 10.0.0.123/31
        ipv6: fc00::fa/126
    bp_interface:
      ipv4: 10.10.246.122/24
      ipv6: fc0a::7c/64
  ARISTA16T3:
    properties:
      - common
      - core
    bgp:
      peer_in_bgp_confed: true
      asn: 65200
      peers:
        65100:
          - 10.0.0.12
          - FC00::19
    interfaces:
      Loopback0:
        ipv4: 100.1.0.8/32
        ipv6: 2064:100::8/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.13/31
        ipv6: FC00::1a/126
    bp_interface:
      ipv4: 10.10.246.8/24
      ipv6: fc0a::e/64
  ARISTA17LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.124
          - fc00::fd
    interfaces:
      Loopback0:
        ipv4: 100.1.0.65/32
        ipv6: 2064:100::3f/128
      Ethernet1:
        ipv4: 10.0.0.125/31
        ipv6: fc00::fe/126
    bp_interface:
      ipv4: 10.10.246.123/24
      ipv6: fc0a::7e/64
  ARISTA18T3:
    properties:
      - common
      - core
    bgp:
      peer_in_bgp_confed: true
      asn: 65200
      peers:
        65100:
          - 10.0.0.20
          - fc00::29
    interfaces:
      Loopback0:
        ipv4: 100.1.0.12/32
        ipv6: 2064:100::12/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Ethernet3:
        lacp: 1
      Ethernet4:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.21/31
        ipv6: fc00::2a/126
    bp_interface:
      ipv4: 10.10.246.12/24
      ipv6: fc0a::16/64
  ARISTA19LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.126
          - fc00::a1
    interfaces:
      Loopback0:
        ipv4: 100.1.0.66/32
        ipv6: 2064:100::4a/128
      Ethernet1:
        ipv4: 10.0.0.127/31
        ipv6: fc00::a2/126
    bp_interface:
      ipv4: 10.10.246.124/24
      ipv6: fc0a::8a/64
  ARISTA20LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.128
          - fc00::a5
    interfaces:
      Loopback0:
        ipv4: 100.1.0.67/32
        ipv6: 2064:100::4b/128
      Ethernet1:
        ipv4: 10.0.0.129/31
        ipv6: fc00::a6/126
    bp_interface:
      ipv4: 10.10.246.125/24
      ipv6: fc0a::8c/64
  ARISTA21LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.130
          - fc00::ad
    interfaces:
      Loopback0:
        ipv4: 100.1.0.68/32
        ipv6: 2064:100::4c/128
      Ethernet1:
        ipv4: 10.0.0.131/31
        ipv6: fc00::ae/126
    bp_interface:
      ipv4: 10.10.246.126/24
      ipv6: fc0a::8e/64
  ARISTA22LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.132
          - fc00::b1
    interfaces:
      Loopback0:
        ipv4: 100.1.0.69/32
        ipv6: 2064:100::4d/128
      Ethernet1:
        ipv4: 10.0.0.133/31
        ipv6: fc00::b2/126
    bp_interface:
      ipv4: 10.10.246.127/24
      ipv6: fc0a::9a/64
  ARISTA23T3:
    properties:
      - common
      - core
    bgp:
      peer_in_bgp_confed: true
      asn: 65200
      peers:
        65100:
          - 10.0.0.14
          - FC00::1d
    interfaces:
      Loopback0:
        ipv4: 100.1.0.9/32
        ipv6: 2064:100::9/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.15/31
        ipv6: FC00::1e/126
    bp_interface:
      ipv4: 10.10.246.9/24
      ipv6: fc0a::10/64
  ARISTA24LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.134
          - fc00::101
    interfaces:
      Loopback0:
        ipv4: 100.1.0.70/32
        ipv6: 2064:100::4e/128
      Ethernet1:
        ipv4: 10.0.0.135/31
        ipv6: fc00::102/126
    bp_interface:
      ipv4: 10.10.246.128/24
      ipv6: fc0a::9c/64
  ARISTA25T3:
    properties:
      - common
      - core
    bgp:
      peer_in_bgp_confed: true
      asn: 65200
      peers:
        65100:
          - 10.0.0.28
          - fc00::39
    interfaces:
      Loopback0:
        ipv4: 100.1.0.16/32
        ipv6: 2064:100::16/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.29/31
        ipv6: fc00::3a/126
    bp_interface:
      ipv4: 10.10.246.16/24
      ipv6: fc0a::1e/64
  ARISTA26LT2:
    properties:
      - common
      - leaf
    bgp:
      asn: 65300
      confed_asn: 65100
      confed_peers: 66000
      peers:
        66000:
          - 10.0.0.136
          - fc00::31
    interfaces:
      Loopback0:
        ipv4: 100.1.0.71/32
        ipv6: 2064:100::4f/128
      Ethernet1:
        ipv4: 10.0.0.137/31
        ipv6: fc00::32/126
    bp_interface:
      ipv4: 10.10.246.129/24
      ipv6: fc0a::9e/64
