topology:
  # 9 DUTs - 1 t1 as npu (dut0) and 8 dpu (dut 1...8)
  dut_num: 9
  topo_type: smartswitch
  VMs:
    ARISTA01T2:
      vlans:
        - 0.0@0
        - 0.1@1
      vm_offset: 0
    ARISTA03T2:
      vlans:
        - 0.2@2
        - 0.3@3
      vm_offset: 1
    ARISTA05T2:
      vlans:
        - 0.4@4
        - 0.5@5
      vm_offset: 2
    ARISTA07T2:
      vlans:
        - 0.6@6
        - 0.7@7
      vm_offset: 3
    ARISTA01T0:
      vlans:
        - 0.8@8
      vm_offset: 4
    ARISTA02T0:
      vlans:
        - 0.9@9
      vm_offset: 5
    ARISTA03T0:
      vlans:
        - 0.10@10
      vm_offset: 6
    ARISTA04T0:
      vlans:
        - 0.11@11
      vm_offset: 7
    ARISTA05T0:
      vlans:
        - 0.12@12
      vm_offset: 8
    ARISTA06T0:
      vlans:
        - 0.13@13
      vm_offset: 9
    ARISTA07T0:
      vlans:
        - 0.14@14
      vm_offset: 10
    ARISTA08T0:
      vlans:
        - 0.15@15
      vm_offset: 11
    ARISTA09T0:
      vlans:
        - 0.16@16
      vm_offset: 12
    ARISTA10T0:
      vlans:
        - 0.17@17
      vm_offset: 13
    ARISTA11T0:
      vlans:
        - 0.18@18
      vm_offset: 14
    ARISTA12T0:
      vlans:
        - 0.19@19
      vm_offset: 15
    ARISTA13T0:
      vlans:
        - 0.20@20
      vm_offset: 16
    ARISTA14T0:
      vlans:
        - 0.21@21
      vm_offset: 17
    ARISTA15T0:
      vlans:
        - 0.22@22
      vm_offset: 18
    ARISTA16T0:
      vlans:
        - 0.23@23
      vm_offset: 19
    ARISTA17T0:
      vlans:
        - 0.24@24
      vm_offset: 20
    ARISTA18T0:
      vlans:
        - 0.25@25
      vm_offset: 21
    ARISTA19T0:
      vlans:
        - 0.26@26
      vm_offset: 22
    ARISTA20T0:
      vlans:
        - 0.27@27
      vm_offset: 23

  DUT:
    loopback:
      ipv4:
        - 10.1.0.1/32
        - 10.1.0.2/32
        - 10.1.0.3/32
        - 10.1.0.4/32
        - 10.1.0.5/32
        - 10.1.0.6/32
        - 10.1.0.7/32
        - 10.1.0.8/32
        - 10.1.0.9/32
      ipv6:
        - FC00:10::1/128
        - FC00:11::1/128
        - FC00:12::1/128
        - FC00:13::1/128
        - FC00:14::1/128
        - FC00:15::1/128
        - FC00:16::1/128
        - FC00:17::1/128
        - FC00:18::1/128

configuration_properties:
  common:
    dut_asn: 65100
    dut_type: LeafRouter
    nhipv4: 10.10.246.254
    nhipv6: FC0A::FF
    podset_number: 200
    tor_number: 20
    tor_subnet_number: 2
    max_tor_subnet_number: 20
    tor_subnet_size: 128
  spine:
    swrole: spine
  tor:
    swrole: tor

configuration:
  ARISTA01T2:
    properties:
    - common
    - spine
    bgp:
      asn: 65200
      peers:
        65100:
        - 10.0.0.0
        - FC00::1
    interfaces:
      Loopback0:
        ipv4: 100.1.0.1/32
        ipv6: 2064:100::1/128
      Ethernet1:
        lacp: 1
        dut_index: 0
      Ethernet2:
        lacp: 1
        dut_index: 0
      Port-Channel1:
        ipv4: 10.0.0.1/31
        ipv6: fc00::2/126
    bp_interface:
      ipv4: 10.10.246.1/24
      ipv6: fc0a::2/64

  ARISTA03T2:
    properties:
    - common
    - spine
    bgp:
      asn: 65200
      peers:
        65100:
        - 10.0.0.4
        - FC00::9
    interfaces:
      Loopback0:
        ipv4: 100.1.0.3/32
        ipv6: 2064:100::3/128
      Ethernet1:
        lacp: 1
        dut_index: 0
      Ethernet2:
        lacp: 1
        dut_index: 0
      Port-Channel1:
        ipv4: 10.0.0.5/31
        ipv6: fc00::a/126
    bp_interface:
      ipv4: 10.10.246.3/24
      ipv6: fc0a::6/64

  ARISTA05T2:
    properties:
    - common
    - spine
    bgp:
      asn: 65200
      peers:
        65100:
        - 10.0.0.8
        - FC00::11
    interfaces:
      Loopback0:
        ipv4: 100.1.0.5/32
        ipv6: 2064:100::5/128
      Ethernet1:
        lacp: 1
        dut_index: 0
      Ethernet2:
        lacp: 1
        dut_index: 0
      Port-Channel1:
        ipv4: 10.0.0.9/31
        ipv6: fc00::12/126
    bp_interface:
      ipv4: 10.10.246.5/24
      ipv6: fc0a::a/64

  ARISTA07T2:
    properties:
    - common
    - spine
    bgp:
      asn: 65200
      peers:
        65100:
        - 10.0.0.12
        - FC00::19
    interfaces:
      Loopback0:
        ipv4: 100.1.0.7/32
        ipv6: 2064:100::7/128
      Ethernet1:
        lacp: 1
        dut_index: 0
      Ethernet2:
        lacp: 1
        dut_index: 0
      Port-Channel1:
        ipv4: 10.0.0.13/31
        ipv6: fc00::1a/126
    bp_interface:
      ipv4: 10.10.246.7/24
      ipv6: fc0a::e/64

  ARISTA01T0:
    properties:
    - common
    - tor
    tornum: 1
    bgp:
      asn: 64001
      peers:
        65100:
        - 10.0.0.32
        - FC00::41
    interfaces:
      Loopback0:
        ipv4: 100.1.0.17/32
        ipv6: 2064:100::11/128
      Ethernet1:
        ipv4: 10.0.0.33/31
        ipv6: fc00::42/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.17/24
      ipv6: fc0a::22/64
    vips:
      ipv4:
        prefixes:
           - 200.0.1.0/26
        asn: 64700

  ARISTA02T0:
    properties:
    - common
    - tor
    tornum: 2
    bgp:
      asn: 64002
      peers:
        65100:
        - 10.0.0.34
        - FC00::45
    interfaces:
      Loopback0:
        ipv4: 100.1.0.18/32
        ipv6: 2064:100::12/128
      Ethernet1:
        ipv4: 10.0.0.35/31
        ipv6: fc00::46/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.18/24
      ipv6: fc0a::25/64

  ARISTA03T0:
    properties:
    - common
    - tor
    tornum: 3
    bgp:
      asn: 64003
      peers:
        65100:
        - 10.0.0.36
        - FC00::49
    interfaces:
      Loopback0:
        ipv4: 100.1.0.19/32
        ipv6: 2064:100::13/128
      Ethernet1:
        ipv4: 10.0.0.37/31
        ipv6: fc00::4a/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.19/24
      ipv6: fc0a::26/64
    vips:
      ipv4:
        prefixes:
          - 200.0.1.0/26
        asn: 64700

  ARISTA04T0:
    properties:
    - common
    - tor
    tornum: 4
    bgp:
      asn: 64004
      peers:
        65100:
        - 10.0.0.38
        - FC00::4D
    interfaces:
      Loopback0:
        ipv4: 100.1.0.20/32
        ipv6: 2064:100::14/128
      Ethernet1:
        ipv4: 10.0.0.39/31
        ipv6: fc00::4e/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.20/24
      ipv6: fc0a::29/64

  ARISTA05T0:
    properties:
    - common
    - tor
    tornum: 5
    bgp:
      asn: 64005
      peers:
        65100:
        - 10.0.0.40
        - FC00::51
    interfaces:
      Loopback0:
        ipv4: 100.1.0.21/32
        ipv6: 2064:100::15/128
      Ethernet1:
        ipv4: 10.0.0.41/31
        ipv6: fc00::52/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.21/24
      ipv6: fc0a::2a/64

  ARISTA06T0:
    properties:
    - common
    - tor
    tornum: 6
    bgp:
      asn: 64006
      peers:
        65100:
        - 10.0.0.42
        - FC00::55
    interfaces:
      Loopback0:
        ipv4: 100.1.0.22/32
        ipv6: 2064:100::16/128
      Ethernet1:
        ipv4: 10.0.0.43/31
        ipv6: fc00::56/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.22/24
      ipv6: fc0a::2d/64

  ARISTA07T0:
    properties:
    - common
    - tor
    tornum: 7
    bgp:
      asn: 64007
      peers:
        65100:
        - 10.0.0.44
        - FC00::59
    interfaces:
      Loopback0:
        ipv4: 100.1.0.23/32
        ipv6: 2064:100::17/128
      Ethernet1:
        ipv4: 10.0.0.45/31
        ipv6: fc00::5a/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.23/24
      ipv6: fc0a::2e/64

  ARISTA08T0:
    properties:
    - common
    - tor
    tornum: 8
    bgp:
      asn: 64008
      peers:
        65100:
        - 10.0.0.46
        - FC00::5D
    interfaces:
      Loopback0:
        ipv4: 100.1.0.24/32
        ipv6: 2064:100::18/128
      Ethernet1:
        ipv4: 10.0.0.47/31
        ipv6: fc00::5e/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.24/24
      ipv6: fc0a::31/64

  ARISTA09T0:
    properties:
    - common
    - tor
    tornum: 9
    bgp:
      asn: 64009
      peers:
        65100:
        - 10.0.0.48
        - FC00::61
    interfaces:
      Loopback0:
        ipv4: 100.1.0.25/32
        ipv6: 2064:100::19/128
      Ethernet1:
        ipv4: 10.0.0.49/31
        ipv6: fc00::62/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.25/24
      ipv6: fc0a::32/64

  ARISTA10T0:
    properties:
    - common
    - tor
    tornum: 10
    bgp:
      asn: 64010
      peers:
        65100:
        - 10.0.0.50
        - FC00::65
    interfaces:
      Loopback0:
        ipv4: 100.1.0.26/32
        ipv6: 2064:100::1a/128
      Ethernet1:
        ipv4: 10.0.0.51/31
        ipv6: fc00::66/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.26/24
      ipv6: fc0a::35/64

  ARISTA11T0:
    properties:
    - common
    - tor
    tornum: 11
    bgp:
      asn: 64011
      peers:
        65100:
        - 10.0.0.52
        - FC00::69
    interfaces:
      Loopback0:
        ipv4: 100.1.0.27/32
        ipv6: 2064:100::1b/128
      Ethernet1:
        ipv4: 10.0.0.53/31
        ipv6: fc00::6a/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.27/24
      ipv6: fc0a::36/64

  ARISTA12T0:
    properties:
    - common
    - tor
    tornum: 12
    bgp:
      asn: 64012
      peers:
        65100:
        - 10.0.0.54
        - FC00::6D
    interfaces:
      Loopback0:
        ipv4: 100.1.0.28/32
        ipv6: 2064:100::1c/128
      Ethernet1:
        ipv4: 10.0.0.55/31
        ipv6: fc00::6e/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.28/24
      ipv6: fc0a::39/64

  ARISTA13T0:
    properties:
    - common
    - tor
    tornum: 13
    bgp:
      asn: 64013
      peers:
        65100:
        - 10.0.0.56
        - FC00::71
    interfaces:
      Loopback0:
        ipv4: 100.1.0.29/32
        ipv6: 2064:100::1d/128
      Ethernet1:
        ipv4: 10.0.0.57/31
        ipv6: fc00::72/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.29/24
      ipv6: fc0a::3a/64

  ARISTA14T0:
    properties:
    - common
    - tor
    tornum: 14
    bgp:
      asn: 64014
      peers:
        65100:
        - 10.0.0.58
        - FC00::75
    interfaces:
      Loopback0:
        ipv4: 100.1.0.30/32
        ipv6: 2064:100::1e/128
      Ethernet1:
        ipv4: 10.0.0.59/31
        ipv6: fc00::76/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.30/24
      ipv6: fc0a::3d/64

  ARISTA15T0:
    properties:
    - common
    - tor
    tornum: 15
    bgp:
      asn: 64015
      peers:
        65100:
        - 10.0.0.60
        - FC00::79
    interfaces:
      Loopback0:
        ipv4: 100.1.0.31/32
        ipv6: 2064:100::1f/128
      Ethernet1:
        ipv4: 10.0.0.61/31
        ipv6: fc00::7a/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.31/24
      ipv6: fc0a::3e/64

  ARISTA16T0:
    properties:
    - common
    - tor
    tornum: 16
    bgp:
      asn: 64016
      peers:
        65100:
        - 10.0.0.62
        - FC00::7D
    interfaces:
      Loopback0:
        ipv4: 100.1.0.32/32
        ipv6: 2064:100::20/128
      Ethernet1:
        ipv4: 10.0.0.63/31
        ipv6: fc00::7e/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.32/24
      ipv6: fc0a::41/64

  ARISTA17T0:
    properties:
    - common
    - tor
    tornum: 17
    bgp:
      asn: 64017
      peers:
        65100:
        - 10.0.0.64
        - FC00::81
    interfaces:
      Loopback0:
        ipv4: 100.1.0.33/32
        ipv6: 2064:100::21/128
      Ethernet1:
        ipv4: 10.0.0.65/31
        ipv6: fc00::82/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.33/24
      ipv6: fc0a::42/64

  ARISTA18T0:
    properties:
    - common
    - tor
    tornum: 18
    bgp:
      asn: 64018
      peers:
        65100:
        - 10.0.0.66
        - FC00::85
    interfaces:
      Loopback0:
        ipv4: 100.1.0.34/32
        ipv6: 2064:100::22/128
      Ethernet1:
        ipv4: 10.0.0.67/31
        ipv6: fc00::86/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.34/24
      ipv6: fc0a::45/64

  ARISTA19T0:
    properties:
    - common
    - tor
    tornum: 19
    bgp:
      asn: 64019
      peers:
        65100:
        - 10.0.0.68
        - FC00::89
    interfaces:
      Loopback0:
        ipv4: 100.1.0.35/32
        ipv6: 2064:100::23/128
      Ethernet1:
        ipv4: 10.0.0.69/31
        ipv6: fc00::8a/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.35/24
      ipv6: fc0a::46/64

  ARISTA20T0:
    properties:
    - common
    - tor
    tornum: 20
    bgp:
      asn: 64020
      peers:
        65100:
        - 10.0.0.70
        - FC00::8D
    interfaces:
      Loopback0:
        ipv4: 100.1.0.36/32
        ipv6: 2064:100::24/128
      Ethernet1:
        ipv4: 10.0.0.71/31
        ipv6: fc00::8e/126
        dut_index: 0
    bp_interface:
      ipv4: 10.10.246.36/24
      ipv6: fc0a::49/64
