topology:
  VMs:
    ARISTA01T0:
      vlans:
        - 0
      vm_offset: 0
    ARISTA02T0:
      vlans:
        - 1
      vm_offset: 1
  
configuration_properties:
  common:
    dut_asn: 65100
    dut_type: SonicHost
    nhipv4: 10.10.246.254
    nhipv6: FC0A::FF
  tor:
    swrole: tor

configuration:
  ARISTA01T0:
    properties:
    - common
    - tor
    tornum: 1
    bgp:
      asn: 65200
      peers:
        65100:
        - 10.0.0.32
        - FC00::41
    vips:
      ipv4:
        prefixes:
          - 200.0.1.0/26
        asn: 64700
    interfaces:
      Loopback0:
        ipv4: 100.1.0.17/32
        ipv6: 2064:100::11/128
      Ethernet1:
        ipv4: 10.0.0.33/31
        ipv6: fc00::42/126
    bp_interface:
      ipv4: 10.10.246.17/24
      ipv6: fc0a::22/64

  ARISTA02T0:
    properties:
    - common
    - tor
    tornum: 2
    bgp:
      asn: 65200
      peers:
        65100:
        - 10.0.0.34
        - FC00::45
    interfaces:
      Loopback0:
        ipv4: 100.1.0.18/32
        ipv6: 2064:100::12/128
      Ethernet1:
        ipv4: 10.0.0.35/31
        ipv6: fc00::46/126
    bp_interface:
      ipv4: 10.10.246.18/24
      ipv6: fc0a::25/64