topology:
  host_interfaces:
    - 0
    - 8
    - 16
    - 24
    - 96
    - 104
    - 112
    - 120
    - 128
    - 136
    - 144
    - 152
    - 224
    - 232
    - 240
    - 248
  VMs:
    ARISTA01T1:
      vlans:
        - 32
      vm_offset: 0
    ARISTA09T1:
      vlans:
        - 40
      vm_offset: 1
    ARISTA17T1:
      vlans:
        - 48
      vm_offset: 2
    ARISTA25T1:
      vlans:
        - 56
      vm_offset: 3
    ARISTA33T1:
      vlans:
        - 64
      vm_offset: 4
    ARISTA41T1:
      vlans:
        - 72
      vm_offset: 5
    ARISTA49T1:
      vlans:
        - 80
      vm_offset: 6
    ARISTA57T1:
      vlans:
        - 88
      vm_offset: 7
    ARISTA65T1:
      vlans:
        - 160
      vm_offset: 8
    ARISTA73T1:
      vlans:
        - 168
      vm_offset: 9
    ARISTA81T1:
      vlans:
        - 176
      vm_offset: 10
    ARISTA89T1:
      vlans:
        - 184
      vm_offset: 11
    ARISTA97T1:
      vlans:
        - 192
      vm_offset: 12
    ARISTA105T1:
      vlans:
        - 200
      vm_offset: 13
    ARISTA113T1:
      vlans:
        - 208
      vm_offset: 14
    ARISTA121T1:
      vlans:
        - 216
      vm_offset: 15
    ARISTA01PT0:
      vlans:
        - 256
      vm_offset: 16
    ARISTA02PT0:
      vlans:
        - 257
      vm_offset: 17
  DUT:
    vlan_configs:
      default_vlan_config: one_vlan_a
      one_vlan_a:
        Vlan1000:
          id: 1000
          intfs: [0, 8, 16, 24, 96, 104, 112, 120, 128, 136, 144, 152, 224, 232, 240, 248]
          prefix_v6: fc02:1000::1/64
          tag: 1000
      two_vlan_a:
        Vlan1000:
          id: 1000
          intfs: [0, 8, 16, 24, 96, 104, 112, 120]
          prefix_v6: fc02:100::1/64
          tag: 1000
        Vlan1100:
          id: 1100
          intfs: [128, 136, 144, 152, 224, 232, 240, 248]
          prefix_v6: fc02:101::1/64
          tag: 1100
      four_vlan_a:
        Vlan1000:
          id: 1000
          intfs: [0, 8, 16, 24]
          prefix_v6: fc02:100::1/64
          tag: 1000
        Vlan1100:
          id: 1100
          intfs: [96, 104, 112, 120]
          prefix_v6: fc02:101::1/64
          tag: 1100
        Vlan1200:
          id: 1200
          intfs: [128, 136, 144, 152]
          prefix_v6: fc02:102::1/64
          tag: 1200
        Vlan1300:
          id: 1300
          intfs: [224, 232, 240, 248]
          prefix_v6: fc02:103::1/64
          tag: 1300

configuration_properties:
  common:
    dut_asn: 4200000000
    dut_type: ToRRouter
    podset_number: 200
    tor_number: 16
    tor_subnet_number: 2
    max_tor_subnet_number: 16
    tor_subnet_size: 128
    spine_asn: 4200200000
    leaf_asn_start: 4200100000
    tor_asn_start: 4200000000
    failure_rate: 0
    nhipv6: FC0A::FF
    ipv6_address_pattern: 2064:100:0::%02X%02X:%02X%02X:0/120
    enable_ipv4_routes_generation: false
    enable_ipv6_routes_generation: true
  leaf:
    swrole: leaf
  tor:
    swrole: tor

configuration:
  ARISTA01T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.33
      asn: 4200100000
      peers:
        4200000000:
          - fc00::81
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:21::/128
      Ethernet1:
        ipv6: fc00::82/126
    bp_interface:
      ipv6: fc0a::22/64
  ARISTA09T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.41
      asn: 4200100000
      peers:
        4200000000:
          - fc00::a1
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:29::/128
      Ethernet1:
        ipv6: fc00::a2/126
    bp_interface:
      ipv6: fc0a::2a/64
  ARISTA17T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.49
      asn: 4200100000
      peers:
        4200000000:
          - fc00::c1
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:31::/128
      Ethernet1:
        ipv6: fc00::c2/126
    bp_interface:
      ipv6: fc0a::32/64
  ARISTA25T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.57
      asn: 4200100000
      peers:
        4200000000:
          - fc00::e1
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:39::/128
      Ethernet1:
        ipv6: fc00::e2/126
    bp_interface:
      ipv6: fc0a::3a/64
  ARISTA33T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.65
      asn: 4200100000
      peers:
        4200000000:
          - fc00::101
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:41::/128
      Ethernet1:
        ipv6: fc00::102/126
    bp_interface:
      ipv6: fc0a::42/64
  ARISTA41T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.73
      asn: 4200100000
      peers:
        4200000000:
          - fc00::121
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:49::/128
      Ethernet1:
        ipv6: fc00::122/126
    bp_interface:
      ipv6: fc0a::4a/64
  ARISTA49T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.81
      asn: 4200100000
      peers:
        4200000000:
          - fc00::141
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:51::/128
      Ethernet1:
        ipv6: fc00::142/126
    bp_interface:
      ipv6: fc0a::52/64
  ARISTA57T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.89
      asn: 4200100000
      peers:
        4200000000:
          - fc00::161
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:59::/128
      Ethernet1:
        ipv6: fc00::162/126
    bp_interface:
      ipv6: fc0a::5a/64
  ARISTA65T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.161
      asn: 4200100000
      peers:
        4200000000:
          - fc00::281
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:a1::/128
      Ethernet1:
        ipv6: fc00::282/126
    bp_interface:
      ipv6: fc0a::a2/64
  ARISTA73T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.169
      asn: 4200100000
      peers:
        4200000000:
          - fc00::2a1
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:a9::/128
      Ethernet1:
        ipv6: fc00::2a2/126
    bp_interface:
      ipv6: fc0a::aa/64
  ARISTA81T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.177
      asn: 4200100000
      peers:
        4200000000:
          - fc00::2c1
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:b1::/128
      Ethernet1:
        ipv6: fc00::2c2/126
    bp_interface:
      ipv6: fc0a::b2/64
  ARISTA89T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.185
      asn: 4200100000
      peers:
        4200000000:
          - fc00::2e1
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:b9::/128
      Ethernet1:
        ipv6: fc00::2e2/126
    bp_interface:
      ipv6: fc0a::ba/64
  ARISTA97T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.193
      asn: 4200100000
      peers:
        4200000000:
          - fc00::301
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:c1::/128
      Ethernet1:
        ipv6: fc00::302/126
    bp_interface:
      ipv6: fc0a::c2/64
  ARISTA105T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.201
      asn: 4200100000
      peers:
        4200000000:
          - fc00::321
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:c9::/128
      Ethernet1:
        ipv6: fc00::322/126
    bp_interface:
      ipv6: fc0a::ca/64
  ARISTA113T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.209
      asn: 4200100000
      peers:
        4200000000:
          - fc00::341
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:d1::/128
      Ethernet1:
        ipv6: fc00::342/126
    bp_interface:
      ipv6: fc0a::d2/64
  ARISTA121T1:
    properties:
    - common
    - leaf
    bgp:
      router-id: 100.1.0.217
      asn: 4200100000
      peers:
        4200000000:
          - fc00::361
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:d9::/128
      Ethernet1:
        ipv6: fc00::362/126
    bp_interface:
      ipv6: fc0a::da/64
  ARISTA01PT0:
    properties:
    - common
    - tor
    bgp:
      router-id: 100.1.1.1
      asn: 64621
      peers:
        4200000000:
          - fc00::401
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:101::/128
      Ethernet1:
        ipv6: fc00::402/126
    bp_interface:
      ipv6: fc0a::102/64
  ARISTA02PT0:
    properties:
    - common
    - tor
    bgp:
      router-id: 100.1.1.2
      asn: 64622
      peers:
        4200000000:
          - fc00::405
    interfaces:
      Loopback0:
        ipv6: 2064:100:0:102::/128
      Ethernet1:
        ipv6: fc00::406/126
    bp_interface:
      ipv6: fc0a::103/64
