topology:
  host_interfaces:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
  disabled_host_interfaces:
    - 2
    - 3
    - 6
    - 7
    - 10
    - 11
    - 18
    - 19
    - 22
    - 23
    - 26
    - 27
    - 30
    - 31
    - 34
    - 35
    - 38
    - 39
    - 46
    - 47
    - 50
    - 51
    - 54
    - 55
  VMs:
    ARISTA01T1:
      vlans:
        - 12
      vm_offset: 0
    ARISTA02T1:
      vlans:
        - 13
      vm_offset: 1
    ARISTA03T1:
      vlans:
        - 14
      vm_offset: 2
    ARISTA04T1:
      vlans:
        - 15
      vm_offset: 3
    ARISTA05T1:
      vlans:
        - 40
      vm_offset: 4
    ARISTA06T1:
      vlans:
        - 41
      vm_offset: 5
    ARISTA07T1:
      vlans:
        - 42
      vm_offset: 6
    ARISTA08T1:
      vlans:
        - 43
      vm_offset: 7
  DUT:
    vlan_configs:
      default_vlan_config: one_vlan_a
      one_vlan_a:
        Vlan1000:
          id: 1000
          intfs: [0, 1, 4, 5, 8, 9, 16, 17, 20, 21, 24, 25, 28, 29, 32, 33, 36, 37, 44, 45, 48, 49, 52, 53]
          prefix: 192.168.0.1/21
          prefix_v6: fc02:1000::1/64
          tag: 1000
      two_vlan_a:
        Vlan100:
          id: 100
          intfs: [0, 1, 4, 5, 8, 9, 16, 17, 20, 21, 24, 25]
          prefix: 192.168.0.1/22
          prefix_v6: fc02:100::1/64
          tag: 100
        Vlan200:
          id: 200
          intfs: [28, 29, 32, 33, 36, 37, 44, 45, 48, 49, 52, 53]
          prefix: 192.168.4.1/22
          prefix_v6: fc02:200::1/64
          tag: 200

configuration_properties:
  common:
    dut_asn: 65100
    dut_type: ToRRouter
    swrole: leaf
    podset_number: 200
    tor_number: 16
    tor_subnet_number: 2
    max_tor_subnet_number: 16
    tor_subnet_size: 128
    spine_asn: 65534
    leaf_asn_start: 64600
    tor_asn_start: 65100
    failure_rate: 0
    nhipv4: 10.10.246.254
    nhipv6: FC0A::FF

configuration:
  ARISTA01T1:
    properties:
    - common
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.0.0.56
        - FC00::71
    interfaces:
      Loopback0:
        ipv4: 100.1.0.1/32
        ipv6: 2064:100::1/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.57/31
        ipv6: fc00::72/126
    bp_interface:
      ipv4: 10.10.246.1/24
      ipv6: fc0a::1/64

  ARISTA02T1:
    properties:
    - common
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.0.0.58
        - FC00::75
    interfaces:
      Loopback0:
        ipv4: 100.1.0.2/32
        ipv6: 2064:100::2/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.59/31
        ipv6: fc00::76/126
    bp_interface:
      ipv4: 10.10.246.2/24
      ipv6: fc0a::2/64

  ARISTA03T1:
    properties:
    - common
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.0.0.60
        - FC00::79
    interfaces:
      Loopback0:
        ipv4: 100.1.0.3/32
        ipv6: 2064:100::3/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.61/31
        ipv6: fc00::7a/126
    bp_interface:
      ipv4: 10.10.246.3/24
      ipv6: fc0a::3/64

  ARISTA04T1:
    properties:
    - common
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.0.0.62
        - FC00::7D
    interfaces:
      Loopback0:
        ipv4: 100.1.0.4/32
        ipv6: 2064:100::4/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.63/31
        ipv6: fc00::7e/126
    bp_interface:
      ipv4: 10.10.246.4/24
      ipv6: fc0a::4/64

  ARISTA05T1:
    properties:
    - common
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.0.0.64
        - FC00::81
    interfaces:
      Loopback0:
        ipv4: 100.1.0.5/32
        ipv6: 2064:100::5/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.65/31
        ipv6: fc00::82/126
    bp_interface:
      ipv4: 10.10.246.5/24
      ipv6: fc0a::5/64

  ARISTA06T1:
    properties:
    - common
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.0.0.66
        - FC00::85
    interfaces:
      Loopback0:
        ipv4: 100.1.0.6/32
        ipv6: 2064:100::6/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.67/31
        ipv6: fc00::86/126
    bp_interface:
      ipv4: 10.10.246.6/24
      ipv6: fc0a::6/64

  ARISTA07T1:
    properties:
    - common
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.0.0.68
        - FC00::89
    interfaces:
      Loopback0:
        ipv4: 100.1.0.7/32
        ipv6: 2064:100::7/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.69/31
        ipv6: fc00::8a/126
    bp_interface:
      ipv4: 10.10.246.7/24
      ipv6: fc0a::7/64

  ARISTA08T1:
    properties:
    - common
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.0.0.70
        - FC00::8D
    interfaces:
      Loopback0:
        ipv4: 100.1.0.8/32
        ipv6: 2064:100::8/128
      Ethernet1:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.71/31
        ipv6: fc00::8e/126
    bp_interface:
      ipv4: 10.10.246.8/24
      ipv6: fc0a::8/64
