topology:
  host_interfaces:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
  disabled_host_interfaces:
    - 0
    - 25
    - 26
    - 27
  VMs:
    P1:
      vlans:
        - 28
      vm_offset: 0
    P2:
      vlans:
        - 29
      vm_offset: 1
    P3:
      vlans:
        - 30
      vm_offset: 2
    P4:
      vlans:
        - 31
      vm_offset: 3
  DUT:
    vlan_configs:
      default_vlan_config: one_vlan_a
      one_vlan_a:
        Vlan1000:
          id: 1000
          intfs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
          prefix: 192.168.0.1/21
          prefix_v6: fc02:1000::1/64
          tag: 1000
      two_vlan_a:
        Vlan100:
          id: 100
          intfs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
          prefix: 192.168.0.1/22
          secondary_subnet: 192.169.0.1/22
          prefix_v6: fc02:100::1/64
          tag: 100
        Vlan200:
          id: 200
          intfs: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
          prefix: 192.168.4.1/22
          prefix_v6: fc02:200::1/64
          tag: 200
      four_vlan_a:
        Vlan1000:
          id: 1000
          intfs: [1, 2, 3, 4, 5, 6]
          prefix: 192.168.0.1/23
          prefix_v6: fc02:400::1/64
          tag: 1000
        Vlan2000:
          id: 2000
          intfs: [7, 8, 9, 10, 11, 12]
          prefix: 192.168.2.1/23
          prefix_v6: fc02:401::1/64
          tag: 2000
        Vlan3000:
          id: 3000
          intfs: [13, 14, 15, 16, 17, 18]
          prefix: 192.168.4.1/23
          prefix_v6: fc02:402::1/64
          tag: 3000
        Vlan4000:
          id: 4000
          intfs: [19, 20, 21, 22, 23, 24]
          prefix: 192.168.6.1/23
          prefix_v6: fc02:403::1/64
          tag: 4000

configuration_properties:
  common:
    dut_asn: 65100
    dut_type: ToRRouter
    swrole: leaf
    nhipv4: 10.10.246.254
    nhipv6: FC0A::FF
    podset_number: 200
    tor_number: 16
    tor_subnet_number: 2
    max_tor_subnet_number: 16
    tor_subnet_size: 128
    spine_asn: 65534
    leaf_asn_start: 64600
    tor_asn_start: 65500
    failure_rate: 0

configuration:
  P1:
    properties:
    - common
    hwsku: cisco-8101-p4-32x100-vs
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.0.0.56
        - FC00::71
    interfaces:
      Loopback0:
        ipv4: 100.1.0.29/32
        ipv6: 2064:100::1d/128
      Ethernet0:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.57/31
        ipv6: fc00::72/126
    bp_interface:
      ipv4: 10.10.246.29/24
      ipv6: fc0a::1d/64

  P2:
    properties:
    - common
    hwsku: cisco-8101-p4-32x100-vs
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.0.0.58
        - FC00::75
    interfaces:
      Loopback0:
        ipv4: 100.1.0.30/32
        ipv6: 2064:100::1e/128
      Ethernet0:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.59/31
        ipv6: fc00::76/126
    bp_interface:
      ipv4: 10.10.246.30/24
      ipv6: fc0a::1e/64

  P3:
    properties:
    - common
    hwsku: cisco-8101-p4-32x100-vs
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.0.0.60
        - FC00::79
    interfaces:
      Loopback0:
        ipv4: 100.1.0.31/32
        ipv6: 2064:100::1f/128
      Ethernet0:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.61/31
        ipv6: fc00::7a/126
    bp_interface:
      ipv4: 10.10.246.31/24
      ipv6: fc0a::1f/64

  P4:
    properties:
    - common
    hwsku: cisco-8101-p4-32x100-vs
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.0.0.62
        - FC00::7D
    interfaces:
      Loopback0:
        ipv4: 100.1.0.32/32
        ipv6: 2064:100::20/128
      Ethernet0:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.63/31
        ipv6: fc00::7e/126
    bp_interface:
      ipv4: 10.10.246.32/24
      ipv6: fc0a::20/64
