topology:
  host_interfaces:
   - 0
   - 1
   - 2
   - 3
   - 4
   - 5
   - 6
   - 7
   - 8
   - 9
   - 10
   - 11
   - 12
   - 13
   - 14
   - 15
   - 16
   - 17
   - 18
   - 19
   - 20
   - 21
   - 22
   - 23
   - 24
   - 25
   - 26
   - 27
   - 28
   - 29
   - 30
   - 31
   - 32
   - 33
   - 34
   - 35
   - 36
   - 37
   - 38
   - 39
   - 40
   - 41
   - 42
   - 43
   - 44
   - 45
   - 46
   - 47
   - 50
   - 51
   - 52
   - 53
   - 56
   - 57
   - 58
   - 59
   - 62
   - 63
   - 64
   - 65
   - 68
   - 69
   - 70
   - 71
   - 72
   - 73
   - 74
   - 75
   - 76
   - 77
   - 78
   - 79
   - 80
   - 81
   - 82
   - 83
   - 84
   - 85
   - 86
   - 87
   - 88
   - 89
   - 90
   - 91
   - 92
   - 93
   - 94
   - 95
   - 96
   - 97
   - 98
   - 99
   - 100
   - 101
   - 102
   - 103
   - 104
   - 105
   - 106
   - 107
   - 108
   - 109
   - 110
   - 111  
   - 112
   - 113
   - 114
   - 115
   - 116
   - 117
   - 118
   - 119
  disabled_host_interfaces:
   - 7
   - 15
   - 23
   - 31
   - 39
   - 47
   - 53
   - 59
   - 65
   - 71
   - 77
   - 79
   - 81
   - 83
   - 87
   - 88
   - 91
   - 95
   - 96
   - 98
   - 102
   - 103
   - 111
   - 119
  VMs:
    ARISTA01T1:
      vlans:
        - 48
        - 49
      vm_offset: 0
    ARISTA02T1:
      vlans:
        - 54
        - 55
      vm_offset: 1
    ARISTA03T1:
      vlans:
        - 60
        - 61
      vm_offset: 2
    ARISTA04T1:
      vlans:
        - 66
        - 67
      vm_offset: 3

  DUT:
    vlan_configs:
      default_vlan_config: one_vlan_a
      one_vlan_a:
        Vlan1000:
          id: 1000
          intfs: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 50, 51, 52, 56, 57, 58, 62, 63, 64, 68, 69, 70, 72, 73, 74, 75, 76, 78, 80, 82, 84, 85, 86, 89, 90, 92, 93, 94, 97, 99, 100, 101, 104, 105, 106, 107, 108, 109, 110, 112, 113, 114, 115, 116, 117, 118]
          prefix: 192.168.0.1/21
          prefix_v6: fc02:1000::1/64
          tag: 1000
      two_vlan_a:
        Vlan100:
          id: 100
          intfs: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 50, 51]
          prefix: 192.168.0.1/22
          prefix_v6: fc02:100::1/64
          tag: 100
        Vlan200:
          id: 200
          intfs: [52, 56, 57, 58, 62, 63, 64, 68, 69, 70, 72, 73, 74, 75, 76, 78, 80, 82, 84, 85, 86, 89, 90, 92, 93, 94, 97, 99, 100, 101, 104, 105, 106, 107, 108, 109, 110, 112, 113, 114, 115, 116, 117, 118]
          prefix: 192.168.4.1/22
          prefix_v6: fc02:200::1/64
          tag: 200

configuration_properties:
  common:
    dut_asn: 4200065100
    dut_type: ToRRouter
    swrole: leaf
    spine_asn: 65534
    leaf_asn_start: 4200064600
    tor_asn_start: 4200065500
    nhipv4: 10.10.246.254
    nhipv6: FC0A::FF

configuration:
  ARISTA01T1:
    properties:
    - common
    bgp:
      asn: 4200064600
      peers:
        4200065100:
        - 10.0.0.32
        - FC00::21
    interfaces:
      Loopback0:
        ipv4: 100.1.0.33/32
        ipv6: 2064:100::33/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.33/31
        ipv6: fc00::22/126
    bp_interface:
      ipv4: 10.10.246.33/24
      ipv6: fc0a::23/64

  ARISTA02T1:
    properties:
    - common
    bgp:
      asn: 4200064600
      peers:
        4200065100:
        - 10.0.0.34
        - FC00::25
    interfaces:
      Loopback0:
        ipv4: 100.1.0.35/32
        ipv6: 2064:100::26/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.35/31
        ipv6: fc00::26/126
    bp_interface:
      ipv4: 10.10.246.35/24
      ipv6: fc0a::26/64

  ARISTA03T1:
    properties:
    - common
    bgp:
      asn: 4200064600
      peers:
        4200065100:
        - 10.0.0.36
        - FC00::29
    interfaces:
      Loopback0:
        ipv4: 100.1.0.37/32
        ipv6: 2064:100::2A/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.37/31
        ipv6: fc00::2A/126
    bp_interface:
      ipv4: 10.10.246.37/24
      ipv6: fc0a::2A/64

  ARISTA04T1:
    properties:
    - common
    bgp:
      asn: 4200064600
      peers:
        4200065100:
        - 10.0.0.38
        - FC00::2D
    interfaces:
      Loopback0:
        ipv4: 100.1.0.39/32
        ipv6: 2064:100::2E/128
      Ethernet1:
        lacp: 1
      Ethernet2:
        lacp: 1
      Port-Channel1:
        ipv4: 10.0.0.39/31
        ipv6: fc00::2E/126
    bp_interface:
      ipv4: 10.10.246.39/24
      ipv6: fc0a::2E/64
      