minigraph_as_xml: minigraph/03-ARISTA02T0.xml
minigraph_bgp:
- addr: 10.0.0.34
  asn: 65100
  name: str-s6000-on-3
  peer_addr: 10.0.0.35
- addr: FC00::45
  asn: 65100
  name: str-s6000-on-3
  peer_addr: FC00::46
minigraph_bgp_asn: 64002
minigraph_console: {}
minigraph_devices: {}
minigraph_hwsku: Arista-VEOS
minigraph_interfaces:
- addr: 10.0.0.35
  alias: Ethernet1
  mask: 255.255.255.254
  name: Ethernet1
  peer_addr: 10.0.0.34
  prefixlen: 31
  subnet: 10.0.0.34/31
- addr: fc00::46
  alias: Ethernet1
  mask: '126'
  name: Ethernet1
  peer_addr: fc00::45
  prefixlen: 126
  subnet: fc00::44/126
- addr: 10.10.246.18
  alias: Ethernet2
  mask: 255.255.255.0
  name: Ethernet2
  prefixlen: 24
  subnet: 10.10.246.0/24
- addr: fc0a::25
  alias: Ethernet2
  mask: '64'
  name: Ethernet2
  prefixlen: 64
  subnet: fc0a::/64
minigraph_lo_interfaces:
- addr: 100.1.0.18
  mask: 255.255.255.255
  name: Loopback0
  prefixlen: 32
- addr: 2064:100::12
  mask: '128'
  name: Loopback0
  prefixlen: 128
minigraph_mgmt: {}
minigraph_mgmt_interface:
  addr: 10.255.0.53
  gwaddr: 10.255.0.1
  mask: 255.255.255.0
  prefixlen: '24'
minigraph_neighbors: {}
minigraph_portchannel_interfaces: []
minigraph_underlay_devices: null
minigraph_underlay_neighbors: null
minigraph_vlan_interfaces: []
