name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

resources:
  repositories:
  - repository: https://mssonic@dev.azure.com/mssonic/internal/_git/sonic-metadata
    type: git
    name: sonic-metadata
    ref: master

schedules:
  - cron: "0 9 * * 1,3,5"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal-202205
    always: true

variables:
  - group: SONIC_IMAGE_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms63-t1-8111-02
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_CISCO_8111_ABOOT_202205)
    displayName: "Image URL"

  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_BRCM_202205)
    displayName: "py_saithrift URL"

  # Testbed specific, to skip and/or include directories
  - name: TESTBED_SPECIFIC
    type: string
    default: ''
    displayName: Testbed specific

  - name: SKIP_TEST_RESULTS_UPLOADING
    type: boolean
    default: false
    displayName: "Skip uploading test results to Kusto"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      TESTBED_SPECIFIC: ${{ parameters.TESTBED_SPECIFIC }}
      SKIP_TEST_RESULTS_UPLOADING: ${{ parameters.SKIP_TEST_RESULTS_UPLOADING }}
