name: NightlyTest_$(Build.DefinitionName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

#schedules:
#  - cron: "0 4 * * 2,6"
#    displayName: Nightly Scheduler
#    branches:
#      include:
#        - internal
#    always: true

resources:
  repositories:
    - repository: sonic-mgmt
      type: github
      name: sonic-net/sonic-mgmt
      ref: master
      endpoint: sonic-net

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: "vms69-t2-8800-1, vmsvc5-t2-8800-1"
    displayName: "Testbed Name"

  - name: MIN_WORKER
    type: string
    default: "1"

  - name: MAX_WORKER
    type: string
    default: "2"

  - name: IMAGE_URL
    type: string
    default: $(IMAGE_CISCO_8000_202405)
    displayName: "Image URL"

  - name: MGMT_BRANCH
    type: string
    default: internal-202405

  # Custom run scripts, if both SCRIPTS and FEATURES are empty, all the test will be executed
  - name: SCRIPTS
    type: string
    default: " "
    displayName: "Scripts to be executed"

  - name: FEATURES
    type: string
    default: " "
    values:
      - " "
      - "copp,decap,everflow,fib,ipfwd"
      - "arp,bgp,lldp,cacl"
      - "snmp,syslog,telemetry,tacacs,ntp,show_techsupport,scp,gnmi"
      - "platform_tests,system_health"
      - "autorestart,container_checker,memory_checker,process_monitoring,monit"
      - "route,ecmp,stress,crm,drop_packets"
      - "acl"
      - "qos,pfcwd"
      - "macsec"
    displayName: "Features to be executed"

  # Custom skip scripts
  - name: SCRIPTS_EXCLUDE
    type: string
    default: "platform_tests/test_kdump.py"
    displayName: "Scripts to be excluded"

  - name: FEATURES_EXCLUDE
    type: string
    default: " "
    displayName: "Features to be excluded"

  # Temporarily disable loganalyzer
  - name: COMMON_EXTRA_PARAMS
    type: string
    default: "--topology t2,any --py_saithrift_url=$(SAITHRIFT_BRCM_202405) --disable_loganalyzer --trim_inv --post_check"
    displayName: "Common test parameters"

  - name: AFFINITY
    type: string
    # For bgp/test_bgp_peer_shutdown.py, it cannot pass on vmsvc5-t2-8800-1 due to incorrect system time.
    # for qos/test_qos_sai there is unstability on lc1-1 vms69
    default: '[
      {"name": "bgp/test_bgp_peer_shutdown.py", "op": "NOT_ON", "value": ["vmsvc5-t2-8800-1"]},
      {"name": "qos/test_qos_sai.py", "op": "NOT_ON", "value": ["vms69-t2-8800-1"]}
    ]'
    displayName: "Test affinity, only support test module(e.g. 'bgp/test_bgp_fact.py')"

  - name: SPECIFIC_PARAM
    type: string
    default: '[
      {"name": "test_posttest.py", "param": "--posttest_show_tech_since=-5days00:00"},
      {"name": "bfd/test_bfd_static_route.py", "param": "--completeness_level=debug"}
    ]'
    displayName: "Specific param, support feature(e.g. 'bgp') or test module(e.g. 'bgp/test_bgp_fact.py')"

  # Test timeout
  - name: MAX_RUN_TEST_MINUTES
    type: number
    default: 8640

  - name: ENABLE_PARALLEL_RUN
    type: string
    default: "True"

stages:
- stage: Test

  variables:
    - group: SONiC-Elastictest

  jobs:
  - job:
    displayName: 8800.t2.202405.NightlyTest_by_Elastictest
    timeoutInMinutes: ${{ parameters.MAX_RUN_TEST_MINUTES }}
    continueOnError: false
    pool: sonic-ubuntu-1c
    steps:
    - template: ../../run-test-nightly-elastictest-template.yml
      parameters:
        TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
        SCRIPTS: ${{ parameters.SCRIPTS }}
        FEATURES: ${{ parameters.FEATURES }}
        SCRIPTS_EXCLUDE: ${{ parameters.SCRIPTS_EXCLUDE }}
        FEATURES_EXCLUDE: ${{ parameters.FEATURES_EXCLUDE }}
        COMMON_EXTRA_PARAMS: ${{ parameters.COMMON_EXTRA_PARAMS }}
        MGMT_BRANCH: ${{ parameters.MGMT_BRANCH }}
        MAX_RUN_TEST_MINUTES: ${{ parameters.MAX_RUN_TEST_MINUTES }}
        ENABLE_PARALLEL_RUN: ${{ parameters.ENABLE_PARALLEL_RUN }}
        IMAGE_URL: ${{ parameters.IMAGE_URL }}
        MIN_WORKER: ${{ parameters.MIN_WORKER }}
        MAX_WORKER: ${{ parameters.MAX_WORKER }}
        AFFINITY: ${{ parameters.AFFINITY }}
        SPECIFIC_PARAM: ${{ parameters.SPECIFIC_PARAM }}
