# Celestica

name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 12 * * *"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms12-9-t0-e1031
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_202012_SLIM)
    displayName: "Image URL"

  # Deploy parameters
  - name: ENABLE_DATAACL
    type: boolean
    default: false

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_BRCM_202012)
    displayName: "py_saithrift URL"

  - name: SKIP_SCRIPTS
    type: string
    default: "memory_checker/test_memory_checker.py \
              arp/test_arp_dualtor.py \
              arp/test_wr_arp.py \
              iface_namingmode/test_iface_namingmode.py::TestShowPriorityGroup
              platform_tests/api/test_psu.py::TestPsuApi::test_power \
              platform_tests/api/test_psu.py::TestPsuApi::test_temperature \
              platform_tests/api/test_psu.py::TestPsuApi::test_led \
              platform_tests/link_flap/test_cont_link_flap.py \
              platform_tests/test_advanced_reboot.py \
              platform_tests/test_cont_warm_reboot.py \
              platform_tests/test_reboot.py::test_warm_reboot \
              platform_tests/test_reboot.py::test_fast_reboot \
              pfc/test_unknown_mac.py \
              route/test_route_perf.py \
              vxlan/test_vnet_vxlan.py \
              vxlan/test_vxlan_decap.py \
              vxlan/test_vnet_route_leak.py"
    displayName: "Skip test scripts"

  # Testbed specific, to skip and/or include directories
  - name: TESTBED_SPECIFIC
    type: string
    default: '-S "ecmp drop_packets dualtor mvrf nat pfc_asym pfcwd platform_tests/mellanox qos restapi snappi span sub_port_interfaces vlan vrf"'
    displayName: Testbed specific

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      SKIP_SCRIPTS: ${{ parameters.SKIP_SCRIPTS }}
      ENABLE_DATAACL: ${{ parameters.ENABLE_DATAACL }}
