linux_image: { name: linux-image-3.16.0-4-amd64 , version: 3.16.7-ckt11-2+acs8u2 }
platform_modules_s6000: { name: platform-modules-s6000 , version: "*" }
opennsl: { name: opennsl-modules-3.16.0-4-amd64 , version: "6.4.5.B*" }
opennslv2: { name: opennsl-modules-3.16.0-4-amd64 , version: "6.4.10*" }
version_sx_kernel: "*"
version_mlnxsdk: "*"
version_iproute2_mlnx: "1.mlnx*"
version_docker_engine: 1.11.1-0~jessie
version_sonic_cli: "*"

image_id_database: docker-database:latest
image_id_snmp: docker-snmp:latest
image_id_lldp: docker-lldp:latest
image_id_platform_monitor: docker-platform-monitor:latest

image_id_syncd: docker-syncd:latest
image_id_syncd_mlnx: docker-syncd-mlnx:latest
image_id_syncd_cavm: docker-syncd-cavm:latest
image_id_syncd_mlnx_rpc: docker-syncd-mlnx-rpc:latest
image_id_orchagent: docker-orchagent:latest
image_id_orchagent_mlnx: docker-orchagent-mlnx:latest
image_id_orchagent_cavm: docker-orchagent-cavm:latest
image_id_fpm: docker-fpm:latest
