name: NightlyTest_$(Build.DefinitionName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none


schedules:
  - cron: "30 7 * * 1,3,5"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

resources:
  repositories:
    - repository: sonic-mgmt
      type: github
      name: sonic-net/sonic-mgmt
      ref: master
      endpoint: sonic-net

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS


parameters:
  - name: TESTBED_NAME
    type: string
    default: "vms18-t1-7050qx-acs-03"
    displayName: "Testbed Name"

  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_ABOOT_202305_SLIM)
    displayName: "Image URL"

  - name: UPGRADE_IMAGE_PARAM
    type: string
    default: "--prev-url $(IMAGE_BRCM_ABOOT_202012_SLIM)"
    displayName: "Upgrade image parameter"

  - name: MGMT_BRANCH
    type: string
    default: internal-202305

  # Custom run scripts, if both SCRIPTS and FEATURES are empty, all the test will be executed
  - name: SCRIPTS
    type: string
    default: " "
    displayName: "Scripts to be executed"

  - name: FEATURES
    type: string
    default: " "
    displayName: "Features to be executed"

  # Custom skip scripts
  - name: SCRIPTS_EXCLUDE
    type: string
    default: "pfcwd/test_pfcwd_warm_reboot.py, platform_tests/test_advanced_reboot.py, platform_tests/test_cont_warm_reboot.py, bgp/test_traffic_shift.py, arp/test_stress_arp.py"
    displayName: "Scripts to be excluded"

  # metadata-scripts relies on the change to clone sonic-metadata as a fixture which is not done, currently skip the feature
  - name: FEATURES_EXCLUDE
    type: string
    default: "metadata-scripts, acl, everflow, dhcp_relay, dualtor, mvrf, nat, pfc_asym, platform_tests"
    displayName: "Features to be excluded"

  - name: COMMON_EXTRA_PARAMS
    type: string
    default: "--topology t1,any --py_saithrift_url=$(SAITHRIFT_BRCM_202305)"
    displayName: "Common test parameters"

  - name: SPECIFIC_PARAM
    type: string
    default: '[
      {"name": "platform_tests/test_reboot.py", "param": "--deselect=platform_tests/test_reboot.py::test_warm_reboot --deselect=platform_tests/test_reboot.py::test_fast_reboot"}
    ]'
    displayName: "Specific param, support feature(e.g. 'bgp') or test module(e.g. 'bgp/test_bgp_fact.py')"

  # Test timeout
  - name: MAX_RUN_TEST_MINUTES
    type: number
    default: 3600

stages:
- stage: Test

  variables:
    - group: SONiC-Elastictest

  jobs:
  - job:
    displayName: 7050qx.t1-backend.202305.NightlyTest_by_Elastictest
    timeoutInMinutes: ${{ parameters.MAX_RUN_TEST_MINUTES }}
    continueOnError: false
    pool: sonic-ubuntu-1c
    steps:
    - template: ../../run-test-nightly-elastictest-template.yml
      parameters:
        TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
        SCRIPTS: ${{ parameters.SCRIPTS }}
        FEATURES: ${{ parameters.FEATURES }}
        SCRIPTS_EXCLUDE: ${{ parameters.SCRIPTS_EXCLUDE }}
        FEATURES_EXCLUDE: ${{ parameters.FEATURES_EXCLUDE }}
        COMMON_EXTRA_PARAMS: ${{ parameters.COMMON_EXTRA_PARAMS }}
        MGMT_BRANCH: ${{ parameters.MGMT_BRANCH }}
        MAX_RUN_TEST_MINUTES: ${{ parameters.MAX_RUN_TEST_MINUTES }}
        IMAGE_URL: ${{ parameters.IMAGE_URL }}
        SPECIFIC_PARAM: ${{ parameters.SPECIFIC_PARAM }}
        UPGRADE_IMAGE_PARAM: ${{ parameters.UPGRADE_IMAGE_PARAM }}
