name: NightlyTest_$(Build.DefinitionName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none


# schedules:
#   - cron: "0 4 * * 1,5"
#     displayName: Nightly Scheduler
#     branches:
#       include:
#         - internal
#     always: true

resources:
  repositories:
    - repository: sonic-mgmt
      type: github
      name: sonic-net/sonic-mgmt
      ref: master
      endpoint: sonic-net

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS


parameters:
  - name: TESTBED_NAME
    type: string
    default: "vms6-t0-7060, vms63-t0-7060-1, vms63-t0-7060-2"
    displayName: "Testbed Name"

  - name: MIN_WORKER
    type: string
    default: "1"

  - name: MAX_WORKER
    type: string
    default: "3"

  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_ABOOT_INTERNAL_SLIM)
    displayName: "Image URL"

  - name: UPGRADE_IMAGE_PARAM
    type: string
    default: "--prev-url $(IMAGE_BRCM_ABOOT_201811)"
    displayName: "Upgrade image parameter"

  - name: MGMT_BRANCH
    type: string
    default: internal

  # Custom run scripts, if both SCRIPTS and FEATURES are empty, all the test will be executed
  - name: SCRIPTS
    type: string
    default: " "
    displayName: "Scripts to be executed"

  - name: FEATURES
    type: string
    default: " "
    displayName: "Features to be executed"

  # Custom skip scripts
  - name: SCRIPTS_EXCLUDE
    type: string
    default: " "
    displayName: "Scripts to be excluded"

  # metadata-scripts relies on the change to clone sonic-metadata as a fixture which is not done, currently skip the feature
  - name: FEATURES_EXCLUDE
    type: string
    default: "metadata-scripts"
    displayName: "Features to be excluded"

  - name: COMMON_EXTRA_PARAMS
    type: string
    default: "--topology t0,any --py_saithrift_url=$(BJW_SAITHRIFT_BRCM_INTERNAL)"
    displayName: "Common test parameters"

  - name: SPECIFIC_PARAM
    type: string
    default: '[
      {"name": "metadata-scripts", "param": "--upgrade_type=warm,fast --base_image_list=$(IMAGE_BRCM_ABOOT_202012_SLIM).PREV.1,$(IMAGE_BRCM_ABOOT_201811) --target_image_list=$(IMAGE_BRCM_ABOOT_202012_SLIM) --metadata_process"}
    ]'
    displayName: "Specific param, support feature(e.g. 'bgp') or test module(e.g. 'bgp/test_bgp_fact.py')"

  # Test timeout
  - name: MAX_RUN_TEST_MINUTES
    type: number
    default: 3600

stages:
- stage: Test

  variables:
    - group: SONiC-Elastictest

  jobs:
  - job:
    displayName: 7060cx.t0.internal.NightlyTest_by_Elastictest
    timeoutInMinutes: ${{ parameters.MAX_RUN_TEST_MINUTES }}
    continueOnError: false
    pool: sonic-ubuntu-1c
    steps:
    - template: ../../run-test-nightly-elastictest-template.yml
      parameters:
        TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
        SCRIPTS: ${{ parameters.SCRIPTS }}
        FEATURES: ${{ parameters.FEATURES }}
        SCRIPTS_EXCLUDE: ${{ parameters.SCRIPTS_EXCLUDE }}
        FEATURES_EXCLUDE: ${{ parameters.FEATURES_EXCLUDE }}
        COMMON_EXTRA_PARAMS: ${{ parameters.COMMON_EXTRA_PARAMS }}
        MGMT_BRANCH: ${{ parameters.MGMT_BRANCH }}
        MAX_RUN_TEST_MINUTES: ${{ parameters.MAX_RUN_TEST_MINUTES }}
        IMAGE_URL: ${{ parameters.IMAGE_URL }}
        UPGRADE_IMAGE_PARAM: ${{ parameters.UPGRADE_IMAGE_PARAM }}
        SPECIFIC_PARAM: ${{ parameters.SPECIFIC_PARAM }}
        MIN_WORKER: ${{ parameters.MIN_WORKER }}
        MAX_WORKER: ${{ parameters.MAX_WORKER }}
