name: NightlyTest_$(Build.DefinitionName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 4 * * 1,3,5"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

resources:
  repositories:
    - repository: sonic-mgmt
      type: github
      name: sonic-net/sonic-mgmt
      ref: master
      endpoint: sonic-net

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: "vms73-ft2-7060x6-4"
    displayName: "Testbed Name"

  - name: MIN_WORKER
    type: string
    default: "1"

  - name: MAX_WORKER
    type: string
    default: "1"

  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_ABOOT_202503)
    displayName: "Image URL"

  - name: MGMT_BRANCH
    type: string
    default: internal-202503-chassis

  # Custom run scripts, if both SCRIPTS and FEATURES are empty, all the test will be executed
  - name: SCRIPTS
    type: string
    default: " "
    displayName: "Scripts to be executed"

  - name: FEATURES
    type: string
    default: " "
    displayName: "Features to be executed"

  # Custom skip scripts
  - name: SCRIPTS_EXCLUDE
    type: string
    default: "vrf/test_vrf.py,vrf/test_vrf_attr.py, mvrf/test_mgmtvrf.py,platform_tests/test_auto_negotiation.py,sflow/test_sflow.py,nat/test_dynamic_nat.py,nat/test_static_nat.py,platform_tests/link_flap/test_cont_link_flap.py"
    displayName: "Scripts to be excluded"

  - name: FEATURES_EXCLUDE
    type: string
    default: "sub_port_interfaces,ptftests,acstests,saitests,scripts,k8s,sai_qualify,metadata-scripts"
    displayName: "Features to be excluded"

  - name: COMMON_EXTRA_PARAMS
    type: string
    default: "--topology ft2,any --py_saithrift_url=$(SAITHRIFT_BRCM_202503) --trim_inv"
    displayName: "Common test parameters"

  # Test timeout
  - name: MAX_RUN_TEST_MINUTES
    type: number
    default: 3600

  - name: RETRY_TIMES
    type: string
    default: 0

stages:
- stage: Test

  variables:
    - group: SONiC-Elastictest

  jobs:
  - job:
    displayName: 7060x6pe.ft2-64.202503.NightlyTest_by_Elastictest
    timeoutInMinutes: ${{ parameters.MAX_RUN_TEST_MINUTES }}
    continueOnError: false
    pool: sonic-ubuntu-1c
    steps:
    - template: ../../run-test-nightly-elastictest-template.yml
      parameters:
        TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
        SCRIPTS: ${{ parameters.SCRIPTS }}
        FEATURES: ${{ parameters.FEATURES }}
        SCRIPTS_EXCLUDE: ${{ parameters.SCRIPTS_EXCLUDE }}
        FEATURES_EXCLUDE: ${{ parameters.FEATURES_EXCLUDE }}
        COMMON_EXTRA_PARAMS: ${{ parameters.COMMON_EXTRA_PARAMS }}
        MGMT_BRANCH: ${{ parameters.MGMT_BRANCH }}
        MAX_RUN_TEST_MINUTES: ${{ parameters.MAX_RUN_TEST_MINUTES }}
        IMAGE_URL: ${{ parameters.IMAGE_URL }}
        MIN_WORKER: ${{ parameters.MIN_WORKER }}
        MAX_WORKER: ${{ parameters.MAX_WORKER }}
        PTF_IMAGE_TAG: internal-202505
        RETRY_TIMES: ${{ parameters.RETRY_TIMES }}
