name: NightlyTest_$(Build.DefinitionName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none


schedules:
  - cron: "0 12 * * 0,2,4"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

resources:
  repositories:
    - repository: sonic-mgmt
      type: github
      name: sonic-net/sonic-mgmt
      ref: master
      endpoint: sonic-net

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: AGENT_POOL
    type: string
    default: nightly
    values:
      - nightly
      - nightly2
      - nightly-svc
      - nightly-bjw
    displayName: "AGENT POOL"

  - name: TESTBED_NAME
    type: string
    default: "testbed-bjw2-can-720dt-3, testbed-bjw2-can-720dt-4"
    displayName: "Testbed Name"

  - name: MIN_WORKER
    type: string
    default: "1"

  - name: MAX_WORKER
    type: string
    default: "1"

  - name: IMAGE_URL
    type: string
    default: $(BJW_IMAGE_BRCM_ABOOT_202405)
    displayName: "Image URL"

  - name: MGMT_BRANCH
    type: string
    default: internal-202405

  # Custom run scripts, if both SCRIPTS and FEATURES are empty, all the test will be executed
  - name: SCRIPTS
    type: string
    default: " "
    displayName: "Scripts to be executed"

  - name: FEATURES
    type: string
    default: " "
    displayName: "Features to be executed"

  # Custom skip scripts
  - name: SCRIPTS_EXCLUDE
    type: string
    default: " "
    displayName: "Scripts to be excluded"

  - name: FEATURES_EXCLUDE
    type: string
    default: " "
    displayName: "Features to be excluded"

  - name: COMMON_EXTRA_PARAMS
    type: string
    default: "--topology m0,any --no_dscp_uniform --unresettable_xcvr_types=SFP"
    displayName: "Common test parameters"

  - name: SPECIFIC_PARAM
    type: string
    default: '[
      {"name": "test_posttest.py", "param": "--posttest_show_tech_since @0"}
    ]'
    displayName: "Specific param, support feature(e.g. 'bgp') or test module(e.g. 'bgp/test_bgp_fact.py')"

  - name: AFFINITY
    type: string
    default: '[]'
    displayName: "Test affinity, only support test module(e.g. 'bgp/test_bgp_fact.py')"

  # Test timeout
  - name: MAX_RUN_TEST_MINUTES
    type: number
    default: 2820  # 47 hours

stages:
- stage: Test

  variables:
    - group: SONiC-Elastictest

  jobs:
  - job:
    displayName: 720dt.m0.202405.NightlyTest_by_Elastictest
    timeoutInMinutes: ${{ parameters.MAX_RUN_TEST_MINUTES }}
    continueOnError: false
    pool: ${{ parameters.AGENT_POOL }}
    steps:
    - template: ../../run-test-nightly-elastictest-template.yml
      parameters:
        TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
        SCRIPTS: ${{ parameters.SCRIPTS }}
        FEATURES: ${{ parameters.FEATURES }}
        SCRIPTS_EXCLUDE: ${{ parameters.SCRIPTS_EXCLUDE }}
        FEATURES_EXCLUDE: ${{ parameters.FEATURES_EXCLUDE }}
        COMMON_EXTRA_PARAMS: ${{ parameters.COMMON_EXTRA_PARAMS }}
        MGMT_BRANCH: ${{ parameters.MGMT_BRANCH }}
        MAX_RUN_TEST_MINUTES: ${{ parameters.MAX_RUN_TEST_MINUTES }}
        IMAGE_URL: ${{ parameters.IMAGE_URL }}
        AFFINITY: ${{ parameters.AFFINITY }}
        SPECIFIC_PARAM: ${{ parameters.SPECIFIC_PARAM }}
        MIN_WORKER: ${{ parameters.MIN_WORKER }}
        MAX_WORKER: ${{ parameters.MAX_WORKER }}
