---
# This Playbook deploys all Ubuntu VMs defined in an inventory file under k8s_vms{msetnumber}_{servernumber}
# 

- hosts: k8s_servers:&k8s_vm_host
  gather_facts: no
  vars_files:
    - vars/azure_storage.yml
  tasks:
  roles:
    - { role: vm_set, action: 'start_k8s' }

