ansible_ssh_user: "{{ secret_group_vars['fanout']['ansible_ssh_user'] }}"
ansible_ssh_password: "{{ secret_group_vars['fanout']['ansible_ssh_pass'] }}"
fanout_mlnx_user: admin
fanout_mlnx_password: admin
fanout_sonic_user: admin
fanout_sonic_password: password

# Credential for accessing the network cli interface
fanout_network_user: "{{ secret_group_vars['fanout']['ansible_eos_user']}}"
fanout_network_password: "{{ secret_group_vars['fanout']['ansible_eos_pass']}}"

# Credential for accessing the Linux shell
fanout_shell_user: "{{ secret_group_vars['fanout']['ansible_ssh_user']}}"
fanout_shell_password: "{{ secret_group_vars['fanout']['ansible_ssh_pass']}}"

#fanout_tacacs_sonic_user: admin
#fanout_tacacs_sonic_password: password
