
name: RepoMerge_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "30 2 * * *"
    displayName: Merge Github to sonic-mgmt-int
    branches:
      include:
        - internal
    always: true

parameters:
  - name: GITHUB_BRANCH
    type: string
    default: master
    displayName: "Github branch name"

  - name: LOCAL_BRANCH
    type: string
    default: internal
    displayName: "Local branch name of sonic-mgmt-int"

  - name: PUSH_BRANCH
    type: string
    default: internal-stage
    displayName: "Push to this branch after merge is done"

stages:

  - stage: RepoMerge
    jobs:

      - job: sonic_mgmt_merge
        timeoutInMinutes: 30
        variables:
          - name: skipComponentGovernanceDetection
            value: true

        steps:

          - checkout: self
            persistCredentials: true

          - script: |
              force=""
              if [ "${{ parameters.PUSH_BRANCH }}" == "internal-stage" ]; then
                force="-f"
              fi

              /bin/bash .azure-pipelines/repo_mgmt/merge.sh -g ${{ parameters.GITHUB_BRANCH }} -l ${{ parameters.LOCAL_BRANCH }} -p ${{ parameters.PUSH_BRANCH }} ${force}
            displayName: Merge sonic-mgmt
