ansible_ssh_pass: "{{ secret_group_vars['str']['ansible_ssh_pass'] }}"
ansible_become_pass: "{{ secret_group_vars['str']['ansible_become_pass'] }}"
sonicadmin_user: "{{ secret_group_vars['str']['sonicadmin_user'] }}"
sonicadmin_password: "{{ secret_group_vars['str']['sonicadmin_password'] }}"
sonicadmin_initial_password: "{{ secret_group_vars['str']['sonicadmin_initial_password'] }}"
lab_admin_pass: "{{ secret_group_vars['str']['lab_admin_pass'] }}"
fanout_admin_user: "{{ secret_group_vars['str']['fanout_admin_user'] }}"
fanout_admin_password: "{{ secret_group_vars['str']['fanout_admin_password'] }}"
lab_tacacs_key: "{{ secret_group_vars['str']['lab_tacacs_key'] }}"

console_login: "{{ console_login_tacacs }}"
