name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 5 * * 0-5"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms20-t0-ixia-2
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_ABOOT_202012_SLIM)
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: " "
    displayName: "py_saithrift URL"

  - name: SKIP_SCRIPTS
    type: string
    default: "test_nbr_health.py ixia/test_ixia_traffic.py"
    displayName: "Skip Scripts"

  - name: EXTRA_PARAMS
    type: string
    default: "--skip_sanity --allow_recover --showlocals --assert plain -rav --collect_techsupport False"
    displayName: "Extra parameters"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      SKIP_SCRIPTS: ${{ parameters.SKIP_SCRIPTS }}
      EXTRA_PARAMS: ${{ parameters.EXTRA_PARAMS }}
