# SONiC

# Remove v1 docker containers
- name: Remove docker-sswsyncd docker container
  include_tasks: sonicdocker.yml
  vars:
    docker_container: docker-sswsyncd
    docker_image: "docker-sswsyncd"
    docker_privileged: yes
    docker_state: absent

- name: Remove sswsyncd docker container
  include_tasks: sonicdocker.yml
  vars:
    docker_container: sswsyncd
    docker_image: "docker-sswsyncd"
    docker_privileged: yes
    docker_state: absent

- name: Ensure MLNX Linux Module is installed
  become: true
  apt: pkg=sx-kernel={{ version_sx_kernel }}
       state=present
       default_release={{ apt_default_release }}
       force=yes

# Install docker containers
- name: Start syncd docker container
  include_tasks: sonicdocker.yml
  vars:
    docker_container: syncd
    docker_image: "{{ image_id_syncd_mlnx_rpc if host_saithrift is defined else image_id_syncd_mlnx }}"
    docker_privileged: yes
    docker_state: reloaded
    docker_volumes: "{{ syncd_docker_volumes }}"
    docker_volumes_from:
    - database
  tags: syncd

# Remove deprecated orchagent container
- name: Remove orchagent docker container
  include_tasks: sonicdocker.yml
  vars:
    docker_container: orchagent
    docker_image: "{{ image_id_orchagent_mlnx }}"
    docker_privileged: yes
    docker_state: absent
  tags: orchagent

- name: Start swss docker container
  include_tasks: sonicdocker.yml
  vars:
    docker_container: swss
    docker_image: "{{ image_id_orchagent_mlnx }}"
    docker_privileged: yes
    docker_state: reloaded
    docker_volumes: "{{ orchagent_docker_volumes }}"
    docker_volumes_from:
    - database
  tags: orchagent
