# SONiC

# Setup Platform
#- include_tasks: platform-cavm.yml

# Install Cavium Host Interface Driver
- name: Install driver package
  become: true
  apt: pkg=xp80PcieEndpoint
       state=present
       force=yes

- name: Copy the port config file based on port sku
  become: true
  copy:
    src: ssw_extra/{{ sonic_hwsku }}/port_config_{{ sonic_portsku }}.ini
    dest: /etc/ssw/{{ sonic_hwsku }}/port_config.ini

# Install docker containers
- name: Start syncd docker container
  include_tasks: sonicdocker.yml
  vars:
    docker_container: syncd
    docker_image: "{{ image_id_syncd_cavm }}"
    docker_privileged: yes
    docker_state: reloaded
    docker_volumes: "{{ syncd_docker_volumes }}"
    docker_volumes_from:
    - database
  when: host_saithrift is not defined
  tags: syncd

# Remove deprecated orchagent container
- name: Remove orchagent docker container
  include_tasks: sonicdocker.yml
  vars:
    docker_container: orchagent
    docker_image: "{{ image_id_orchagent_cavm }}"
    docker_privileged: yes
    docker_state: absent
  tags: orchagent

- name: Start swss docker container
  include_tasks: sonicdocker.yml
  vars:
    docker_container: swss
    docker_image: "{{ image_id_orchagent_cavm }}"
    docker_privileged: yes
    docker_state: reloaded
    docker_volumes: "{{ orchagent_docker_volumes }}"
    docker_volumes_from:
    - database
  tags: orchagent
