name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pr: none
trigger: none

parameters:
- name: BUILD_REASON
  type: string
  default: "PullRequest"

- name: BUILD_BRANCH
  type: string
  default: " "

- name: TEST_PLAN_NUM
  type: string
  default: "1"

- name: TEST_PLAN_STOP_ON_FAILURE
  type: string
  default: "True"

- name: RETRY_TIMES
  type: string
  default: "2"

- name: MGMT_COMMIT_HASH
  type: string
  default: " "

# Keys: "dpu_checker","dualtor_checker","t0-2vlans_checker","t0-sonic_checker","t0_checker","t1-multi-asic_checker","t1_checker","t2_checker"
# Example: {"t0_checker": ["bgp/test_bgp_command.py", "bgp/test_ping_bgp_neighbor.py"], "t1_checker": ["bgp/test_bgp_fact.py"]}
- name: IMPACT_AREA_INFO
  type: object
  default: {}

stages:
- stage: Test
  variables:
  - group: SONiC-Elastictest
  - name: inventory
    value: veos_vtb
  - name: testbed_file
    value: vtestbed.yaml
  - name: BUILD_BRANCH
    value: ${{ parameters.BUILD_BRANCH }}

  jobs:
    - template: pr_test_template.yml
      parameters:
        BUILD_REASON: ${{ parameters.BUILD_REASON }}
        TEST_PLAN_NUM: ${{ parameters.TEST_PLAN_NUM }}
        RETRY_TIMES: ${{ parameters.RETRY_TIMES }}
        TEST_PLAN_STOP_ON_FAILURE: ${{ parameters.TEST_PLAN_STOP_ON_FAILURE }}
        MGMT_COMMIT_HASH: ${{ parameters.MGMT_COMMIT_HASH }}
        IMPACT_AREA_INFO: ${{ parameters.IMPACT_AREA_INFO }}
