name: Process the Issue Report
on:
  issues:
    types: [opened]
jobs:
  apply-type-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install @octokit/action
      - run: npm install @actions/github
      - run: |
          cat << EOF > apply-label-tmp.mjs
          import { Octokit } from "@octokit/action";
          import { context } from "@actions/github";
          const octokit = new Octokit();
          const input = context.payload.issue.body;
          const issueTypeSection = input.match(/### Issue Type([\s\S]*?)###/);
          var selectedCheckboxes = [];
          if (issueTypeSection) {
            // Match all selected checkboxes (- [x] ...)
            selectedCheckboxes = [...issueTypeSection[1].matchAll(/- \[x\] (.+)/g)].map(match => match[1].trim());
            console.log(selectedCheckboxes); // Output: ["Bug", "Enhancement", "Regression"]
          } else {
            console.log("No 'Issue Type' section found.");
          }
          console.log('Issue Body:', input);
          console.log('Issue Type Selection:', issueTypeSection);
          console.log('Selected Checkboxes:', selectedCheckboxes);
          selectedCheckboxes.forEach(issueType => {
            if (issueType === 'Test Gap') {
              octokit.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['Test gap']
              });
            }
            if (issueType === 'Bug') {
              octokit.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['Bug']
              });
            }
            if (issueType === 'Enhancement') {
              octokit.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['Enhancement']
              });
            }
            if (issueType === 'Regression') {
              octokit.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['regression']
              });
            }
          });
          EOF
          node apply-label-tmp.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
