name: BranchSync

on:
  # Automatically trigger at 00:00(UTC) everyday
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  branch_sync:
    if: github.repository_owner == 'Azure'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup env
        run: |
          set -ex

          sudo apt update
          sudo apt install -y gh jq

          git config --global user.email "sonicbld@microsoft.com"
          git config --global user.name "Sonic Automation"
          git config --global pull.rebase false

          sudo rm -rf sonic-mgmt.msft
          git clone https://github.com/Azure/sonic-mgmt.msft

      - name: Sync code from 202412 to 202503
        run: |
          set -ex

          src_branch="202412"
          target_branch="202503"

          pushd sonic-mgmt.msft

          # Checkout src branch and target branch
          git checkout $src_branch
          git pull origin $src_branch

          git checkout $target_branch
          git pull origin $target_branch

          if ! git merge --no-ff -m "Sync from $src_branch to $target_branch" $src_branch;then
            echo "Merge conflict detected between $src_branch and $target_branch"
            git merge --abort
            exit 1
          fi

          # push code
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Azure/sonic-mgmt.msft $target_branch

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Teams Notification
        if: failure()
        run: |
          curl -H 'Content-Type: application/json' -d '{
            "text": "** Sync fails from 202412 to 202503 **\n
            - **repo:** '${{ github.repository }}'\n
            - **workflow:** '${{ github.workflow }}'\n
            - **trigger:** '${{ github.actor }}'\n
            - **details:** [details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          }' "${{ secrets.TEAMS_WEBHOOK_URL }}"
