---
ansible_user: use_own_value
ansible_password: use_own_value
ansible_become_password: use_own_value

# Use the following username/password variables to login to vm hosts
# instead of the default variables (defined above).
vm_host_user: daweihuang
vm_host_password: GP!8!s5rlwrzgpidmsft
vm_host_become_password: GP!8!s5rlwrzgpidmsft
