root_path: /home/azure/veos-vm
vm_images_url: https://acsbe.blob.core.windows.net/vmimages
cd_image_filename: Aboot-veos-serial-8.0.0.iso
hdd_image_filename: vEOS-lab-4.15.9M.vmdk
skip_image_downloading: false

vm_console_base: 7000
memory: 2097152

# proxy
proxy_env:
  http_proxy: http://10.252.0.99:3128
  https_proxy: http://10.252.0.99:3128

